"""``/api/v1/comfyui`` - version, updater, official templates, and opening a
workflow inside ComfyUI (C8).

Two routes here can start a process: the updater run route and the open-workflow
route when it is asked to start ComfyUI.  Both use the same deliberately awkward
contract: the caller first fetches the matching plan route, shows the resolved
absolute path, and sends that exact path back as a confirmation field.  A
confirmation that does not name what will run is not a confirmation, and
clicking "open a workflow" is never on its own consent to start a program.

Everything else here is read-only.
"""

from __future__ import annotations

from fastapi import APIRouter, Depends, Query, Request

from ...core import config_service
from ...core import db as dbmod
from ...core.errors import AppError
from ...services import comfyui_service
from ...services.queries import workflows_query
from ..deps import Page, page_params, require_stream_capacity, sse_response, sse_stream
from ..middleware import ApiError, normalize_code
from ..schemas.comfyui import (
    ComfyUIInfo,
    LatestVersion,
    LaunchStatus,
    OpenWorkflowPlan,
    OpenWorkflowRequest,
    OpenWorkflowResponse,
    TemplateCatalogue,
    UpdatePlan,
    UpdateRunRequest,
    UpdateRunResponse,
    UpdateStatus,
    WorkflowOrigins,
)
from ..schemas.common import BASE_ERRORS, MUTATION_ERRORS, error_responses

router = APIRouter(prefix="/comfyui", tags=["ComfyUI"])


def _reraise(exc: AppError) -> None:
    raise ApiError(normalize_code(exc.code), exc.message,
                   details=exc.details) from exc


#: SECURITY_REVIEW S-04.  ``discover_updaters`` builds its candidates from
#: ``<comfyui_path>.parent / "update"``, and ``PATCH /system/config`` accepts any
#: directory holding ``models/`` plus ``main.py`` - so a staged directory could
#: get its own ``update\update_comfyui.bat`` offered as the confirmed updater.
#: The confirmation was honest about *what* would run; it was the *which install*
#: question that was under-validated.  Requiring ``comfyui_version.py`` as well
#: raises the bar to a file only a real ComfyUI checkout or portable build has:
#: it is generated by ComfyUI's own release process and is exactly what
#: ``comfyui_service.read_version`` already parses.
#:
#: SECURITY_REVIEW S-20 moved the rule itself into ``comfyui_service`` so the
#: launcher is held to it too: nominating an executable and running one are the
#: same decision, and the launcher reads the same caller-settable path.
INSTALL_PROOF = comfyui_service.INSTALL_PROOF


def _require_verified_install() -> None:
    """Refuse the updater routes unless the configured path is a real install."""
    root = config_service.comfyui_root()
    missing = comfyui_service.missing_install_proof(root)
    if missing:
        raise ApiError(
            "NOT_FOUND",
            "The configured ComfyUI folder is not a verified install, so no "
            "updater is offered for it. A real install carries "
            "comfyui_version.py, main.py and models/.",
            details={"path": str(root) if root else None, "missing": missing})


@router.get("/info", response_model=ComfyUIInfo, responses=BASE_ERRORS,
            summary="Installed version, install flavour, packages, and updaters")
def info() -> dict:
    return comfyui_service.report()


@router.get("/latest", response_model=LatestVersion, responses=BASE_ERRORS,
            summary="Newest published release (read-only; offline is a 200)")
async def latest(
    force: bool = Query(False, description="Bypass the 6-hour cache."),
) -> dict:
    return await comfyui_service.check_latest(force=force)


@router.get("/update/plan", response_model=UpdatePlan,
            responses={**error_responses("NOT_FOUND", "CONFLICT"), **BASE_ERRORS},
            summary="Exactly what would run, so the user can confirm it")
def update_plan(
    updater: str | None = Query(None, description="Updater id; omit for the "
                                                  "recommended one."),
) -> dict:
    _require_verified_install()
    try:
        chosen = comfyui_service.resolve_updater(updater)
    except AppError as exc:
        _reraise(exc)
        raise
    install = comfyui_service.probe()
    running = comfyui_service.is_running()
    warnings: list[str] = []
    if chosen["id"] == "git" and (install.git or {}).get("shallow"):
        warnings.append(
            "This checkout is shallow, so 'git pull --ff-only' may refuse to "
            "fast-forward. The portable updater handles that case.")
    if chosen["id"] == "portable_with_deps":
        warnings.append(
            "This variant reinstalls Python dependencies. Only run it if "
            "dependencies are actually broken.")
    warnings.append("Restart ComfyUI after the update, then re-scan the vault.")

    resolved = chosen.get("path") or ""
    return {
        "updater": chosen["id"], "label": chosen["label"], "path": resolved,
        "working_dir": chosen.get("working_dir"), "command": chosen.get("command", []),
        "confirm_path": resolved,
        "running": running,
        "can_run": bool(resolved) and not running["running"],
        "blocked_reason": ("comfyui_running" if running["running"]
                           else None if resolved else "updater_path_unresolved"),
        "warnings": warnings,
        "alternatives": [u for u in install.updaters if u["id"] != chosen["id"]],
    }


@router.get("/update/status", response_model=UpdateStatus, responses=BASE_ERRORS,
            summary="State of the current or last update run")
def update_status() -> dict:
    return comfyui_service.update_status()


@router.post("/update/run", status_code=202, response_model=UpdateRunResponse,
             responses={**error_responses("NOT_FOUND", "CONFLICT",
                                          "VALIDATION_ERROR"),
                        **MUTATION_ERRORS},
             summary="Run the confirmed updater (never automatic, never scheduled)")
def update_run(body: UpdateRunRequest) -> dict:
    _require_verified_install()
    try:
        return comfyui_service.run_updater(body.updater,
                                           confirm_path=body.confirm_path,
                                           trigger="api")
    except AppError as exc:
        _reraise(exc)
        raise


@router.get("/update/stream", include_in_schema=True, responses=BASE_ERRORS,
            summary="Live updater output (SSE): output, done, error, heartbeat")
async def update_stream(request: Request):
    require_stream_capacity(comfyui_service.UPDATE_CHANNEL)
    return sse_response(
        sse_stream(comfyui_service.UPDATE_CHANNEL.subscribe(), request,
                   close_on_done=True))


@router.get("/open-workflow/plan", response_model=OpenWorkflowPlan,
            responses={**error_responses("NOT_FOUND", "VALIDATION_ERROR"),
                       **BASE_ERRORS},
            summary="What opening this workflow in ComfyUI would do, before it does")
def open_workflow_plan(
    uid: str = Query(..., min_length=3, max_length=64,
                     description="A workflow uid, 'workflow:<id>'."),
    launcher: str | None = Query(None, max_length=80,
                                 description="Launcher id; omit for the "
                                             "recommended one."),
) -> dict:
    try:
        return comfyui_service.open_workflow_plan(uid, launcher)
    except AppError as exc:
        _reraise(exc)
        raise


@router.post("/open-workflow", response_model=OpenWorkflowResponse,
             responses={**error_responses("NOT_FOUND", "CONFLICT",
                                          "VALIDATION_ERROR", "PATH_NOT_ALLOWED"),
                        **MUTATION_ERRORS},
             summary="Open a workflow in ComfyUI; starting it is a separate consent")
def open_workflow(body: OpenWorkflowRequest) -> dict:
    """Three consents, never merged into one.

    Opening a URL is free.  Copying the file into the ComfyUI installation is a
    write and needs ``confirm_copy_destination``.  Starting ComfyUI is running a
    program and needs ``start`` plus ``confirm_launcher_path`` naming the exact
    resolved path the plan showed - clicking "open" never starts anything.
    """
    try:
        return comfyui_service.open_workflow(
            body.uid, launcher_id=body.launcher, start=body.start,
            confirm_launcher_path=body.confirm_launcher_path,
            copy_to_user_workflows=body.copy_to_user_workflows,
            confirm_copy_destination=body.confirm_copy_destination,
            trigger="api")
    except AppError as exc:
        _reraise(exc)
        raise


@router.get("/launch/status", response_model=LaunchStatus, responses=BASE_ERRORS,
            summary="State of the current or last ComfyUI start")
def launch_status() -> dict:
    return comfyui_service.launch_status()


@router.get("/launch/stream", include_in_schema=True, responses=BASE_ERRORS,
            summary="Live start-up progress (SSE): phase, waiting, ready, error, done")
async def launch_stream(request: Request):
    require_stream_capacity(comfyui_service.LAUNCH_CHANNEL)
    return sse_response(
        sse_stream(comfyui_service.LAUNCH_CHANNEL.subscribe(), request,
                   close_on_done=True))


@router.get("/templates", response_model=TemplateCatalogue, responses=BASE_ERRORS,
            summary="Official ComfyUI workflow templates shipped with this install")
def templates(
    page: Page = Depends(page_params),
    bundle: str | None = Query(None, max_length=80),
    q: str | None = Query(None, max_length=120),
) -> dict:
    return comfyui_service.template_catalogue(
        limit=page.limit, offset=page.offset, bundle=bundle, q=q)


@router.get("/workflow-origins", response_model=WorkflowOrigins,
            responses=BASE_ERRORS,
            summary="Indexed workflows grouped by origin, plus the official catalogue")
def workflow_origins(
    include_templates: bool = Query(
        True, description="Also return the official template catalogue summary."),
) -> dict:
    groups = workflows_query.origin_groups()
    indexed_total = sum(int(g["count"]) for g in groups)
    catalogue = (comfyui_service.template_catalogue(limit=1, offset=0)
                 if include_templates
                 else {"available": False, "reason": "not_requested", "items": [],
                       "total": 0, "bundles": []})
    if include_templates and catalogue.get("available"):
        # Listed alongside the indexed groups so the owner sees their official
        # templates in one place, but counted separately: these are catalogued
        # read-only from the ComfyUI distribution, not vault rows.
        groups.append({
            "origin": "official_template",
            "label": "official template",
            "package": None,
            "count": int(catalogue.get("total") or 0),
            "runnable": 0, "broken": 0,
            "catalogued_only": True,
        })
    return {
        "total": indexed_total,
        "indexed_total": indexed_total,
        "catalogued_total": int(catalogue.get("total") or 0),
        "groups": groups,
        "official_templates": catalogue,
    }


@router.get("/path-policy", responses=BASE_ERRORS,
            summary="What happens to existing rows when the ComfyUI path changes")
def path_policy() -> dict:
    """C7.3 - the UI must be able to state this plainly before a path is saved."""
    from ...services import storage_service

    report = storage_service.roots_report()
    cfg = config_service.get_config()
    return {
        "policy": "retain",
        "summary": ("Rows indexed under the previous ComfyUI folder are kept. "
                    "Nothing is deleted when you change the path."),
        "details": [
            "The old root is retired, not removed: its models, workflows and "
            "outputs stay in the vault with their ratings, tags, notes and "
            "album membership intact.",
            "Retired roots are skipped by the missing-file sweep, so the old "
            "library survives even if that drive is later disconnected.",
            "File operations (rename, move, delete) are refused for retired "
            "roots - only configured roots are writable.",
            "Extra model roots from extra_model_paths.yaml are re-read from the "
            "new install; they are never silently carried over.",
            "Remove retired content explicitly from Storage when you are sure.",
        ],
        "reindex_recommended": True,
        "current_roots": len(cfg.roots),
        "retired_roots": report["retired_roots"],
        "retired_bytes": report["retired_bytes"],
        "checked_at": dbmod.now_ms(),
    }
