"""C6 vocabulary, in exactly one place.

REQUIREMENTS_R2 C6 forbids naming an AI coding assistant or AI vendor **as an
author, contributor, or tool** — in README, docs, code comments, UI strings,
commit messages, or ``package.json``.  The product is authored by
*Geekatplay — Vladimir Chopine*, full stop.

What it does **not** forbid is the vendor strings themselves.  ComfyUI ships API
nodes whose class names carry vendor prefixes, and ``parsers/workflow_graph.py``
has to recognise them to tag a workflow as calling out to a hosted service.  A
bare substring scan flags that legitimate feature and, worse, flags every test
that tries to enforce C6 — so the checks below match **attribution shapes**.

This module is the single place the vocabulary is spelled out, and it is the one
file the repo-wide scan skips.  Keeping it here means the scan does not trip over
the scanner.
"""

from __future__ import annotations

import re

# Attribution phrasings, not bare vendor tokens.
PATTERNS: tuple[str, ...] = (
    r"co-?authored[-\s]?by\s*:?\s*[^\n]{0,60}?"
    r"(claude|anthropic|copilot|chat\s?gpt|gpt-[45]|cursor)",
    r"(generated|written|authored|created|built|assisted|made)\s+"
    r"(with|by|using)\s+[^\n]{0,20}?"
    r"(claude|anthropic|copilot|chat\s?gpt|gpt-[45]|cursor|an ai\b|ai assistant)",
    r"(claude|anthropic|copilot|chat\s?gpt|cursor)"
    r"(\s+code)?\s+(wrote|generated|authored|assisted|helped)",
    r"powered by\s+(claude|anthropic|openai|chat\s?gpt)",
    r"\U0001F916\s*generated",
)

COMPILED: tuple[re.Pattern[str], ...] = tuple(
    re.compile(p, re.IGNORECASE) for p in PATTERNS)

# Bare vendor tokens.  Only ever applied to files that have no legitimate reason
# to mention a vendor at all: launcher scripts, package manifests, UI strings.
BARE_TOKENS: tuple[str, ...] = (
    "claude", "anthropic", "copilot", "chatgpt", "cursor.so",
    "ai-generated", "generated by ai",
)

AUTHOR = "Geekatplay"
AUTHOR_FULL = "Vladimir Chopine"


def attribution_hits(text: str) -> list[str]:
    """Every attribution phrase in ``text``, as matched."""
    return [m.group(0) for rx in COMPILED for m in rx.finditer(text)]


def bare_token_hits(text: str) -> list[str]:
    low = text.lower()
    return [t for t in BARE_TOKENS if t in low]
