"""C8 - version detection, updater discovery, and the confirmation guard.

No test here ever executes an updater.  The one that could is the confirm-path
guard, and it asserts the *refusal*: running an installer is a user decision, not
a test fixture.
"""

from __future__ import annotations

import sys
from pathlib import Path

import pytest

BACKEND = Path(__file__).resolve().parent.parent
if str(BACKEND) not in sys.path:
    sys.path.insert(0, str(BACKEND))

from app.core import config_service  # noqa: E402
from app.core import db as dbmod  # noqa: E402
from app.core.errors import NotFoundError, ValidationError  # noqa: E402
from app.core.migrations import migrate  # noqa: E402
from app.parsers import workflow_origin  # noqa: E402
from app.services import comfyui_service as cs  # noqa: E402


def _portable(base: Path, version: str = "0.33.0") -> Path:
    """The real portable layout: ComfyUI, python_embeded and update as siblings."""
    root = base / "ComfyUI"
    (root / "models" / "checkpoints").mkdir(parents=True, exist_ok=True)
    (root / "custom_nodes").mkdir(parents=True, exist_ok=True)
    (root / "output").mkdir(parents=True, exist_ok=True)
    (root / "main.py").write_text("# ComfyUI\n", encoding="utf-8")
    (root / "comfyui_version.py").write_text(
        "# generated by the build\n"
        f'__version__ = "{version}"\n', encoding="utf-8")

    site = base / "python_embeded" / "Lib" / "site-packages"
    site.mkdir(parents=True, exist_ok=True)
    (base / "python_embeded" / "python.exe").write_bytes(b"MZ")
    for dist, dist_version in (("comfyui_frontend_package", "1.49.6"),
                               ("comfyui_workflow_templates_json", "0.1.49"),
                               ("comfyui_embedded_docs", "0.5.10")):
        (site / f"{dist}-{dist_version}.dist-info").mkdir(exist_ok=True)
    templates = site / "comfyui_workflow_templates_json" / "templates"
    templates.mkdir(parents=True, exist_ok=True)
    for name in ("alpha_flow", "beta_flow"):
        (templates / f"{name}.json").write_text('{"nodes": []}', encoding="utf-8")

    update = base / "update"
    update.mkdir(exist_ok=True)
    (update / "update_comfyui.bat").write_text("@echo off\n", encoding="utf-8")
    (update / "update_comfyui_stable.bat").write_text("@echo off\n", encoding="utf-8")
    (base / "run_nvidia_gpu.bat").write_text("@echo off\n", encoding="utf-8")
    return root


@pytest.fixture
def portable(tmp_path):
    db = tmp_path / "comfyui.db"
    original = dbmod.db_path()
    dbmod.set_db_path(db)
    migrate()
    config_service.invalidate()
    root = _portable(tmp_path)
    config_service.set_config({"comfyui_path": str(root), "is_configured": True})
    yield {"root": root, "base": tmp_path}
    dbmod.shutdown_writer()
    dbmod.close_thread_connections()
    dbmod.set_db_path(original)
    config_service.invalidate()


# ---------------------------------------------------------------------------
# C8.1 - version and flavour
# ---------------------------------------------------------------------------

def test_version_is_read_not_executed(portable):
    install = cs.probe()
    assert install.version == "0.33.0"
    assert install.version_source == "comfyui_version.py"


def test_flavour_and_evidence(portable):
    install = cs.probe()
    assert install.flavour == "portable"
    assert install.flavour_reasons, "the UI must be able to say *why* it decided"
    assert install.python and "python_embeded" in install.python


def test_frontend_and_template_package_versions(portable):
    packages = cs.probe().packages
    assert packages.get("comfyui_frontend_package") == "1.49.6"
    assert packages.get("comfyui_workflow_templates_json") == "0.1.49"


def test_version_comparison(portable):
    assert cs.compare_versions("0.33.0", "0.34.1") == "behind"
    assert cs.compare_versions("0.33.0", "0.33.0") == "current"
    assert cs.compare_versions("0.34.0", "v0.33.0") == "ahead"
    assert cs.compare_versions(None, "0.33.0") == "unknown"
    assert cs.compare_versions("0.33.0", "nightly") == "unknown"


# ---------------------------------------------------------------------------
# C8.2 - the latest-version check degrades, never fails
# ---------------------------------------------------------------------------

def test_latest_check_is_a_plain_answer_when_offline(portable):
    import asyncio

    result = asyncio.run(cs.check_latest())
    assert result["installed"] == "0.33.0"
    assert result["state"] in ("current", "behind", "ahead", "unknown")
    assert result["reason"] == "online_disabled"
    assert result["latest"] is None


# ---------------------------------------------------------------------------
# C8.3 - updater discovery and the confirmation guard
# ---------------------------------------------------------------------------

def test_updaters_are_discovered_beside_the_comfyui_folder(portable):
    updaters = {u["id"]: u for u in cs.probe().updaters}
    assert "portable" in updaters, "update/update_comfyui.bat was not found"
    assert "portable_stable" in updaters
    chosen = updaters["portable"]
    assert chosen["recommended"]
    assert Path(chosen["path"]).name == "update_comfyui.bat"
    assert Path(chosen["path"]).is_file()
    assert chosen["command"] == [chosen["path"]]


def test_updater_discovery_reports_nothing_rather_than_guessing(tmp_path):
    """An install with no updater must say so, not invent a path."""
    db = tmp_path / "bare.db"
    original = dbmod.db_path()
    dbmod.set_db_path(db)
    try:
        migrate()
        config_service.invalidate()
        root = tmp_path / "bare" / "ComfyUI"
        (root / "models").mkdir(parents=True)
        (root / "main.py").write_text("#\n", encoding="utf-8")
        config_service.set_config({"comfyui_path": str(root)})
        assert cs.probe().updaters == []
        with pytest.raises(NotFoundError):
            cs.resolve_updater()
    finally:
        dbmod.shutdown_writer()
        dbmod.close_thread_connections()
        dbmod.set_db_path(original)
        config_service.invalidate()


def test_run_refuses_a_confirmation_that_names_the_wrong_path(portable):
    """The rail that makes 'you are about to run X' true (C8.3)."""
    with pytest.raises(ValidationError) as excinfo:
        cs.run_updater("portable", confirm_path=str(portable["base"] / "nope.bat"))
    details = excinfo.value.details
    assert details["resolved_path"].endswith("update_comfyui.bat")
    assert cs.update_status()["status"] != "running", "nothing may have started"


def test_run_refuses_an_empty_confirmation(portable):
    with pytest.raises(ValidationError):
        cs.run_updater("portable", confirm_path="")
    assert cs.update_status()["status"] != "running"


def test_unknown_updater_is_rejected_before_anything_resolves(portable):
    with pytest.raises(NotFoundError):
        cs.resolve_updater("definitely-not-an-updater")


def test_running_probe_is_honest_about_its_confidence(portable):
    probe = cs.is_running()
    assert probe["confidence"] == "inferred"
    assert "method" in probe and probe["note"]


# ---------------------------------------------------------------------------
# C8.4 - templates and workflow origin
# ---------------------------------------------------------------------------

def test_official_templates_are_catalogued_read_only(portable):
    catalogue = cs.template_catalogue()
    assert catalogue["available"]
    assert catalogue["total"] == 2
    assert {i["id"] for i in catalogue["items"]} == {"alpha_flow", "beta_flow"}
    assert all(i["origin"] == "official_template" for i in catalogue["items"])
    assert "not indexed" in (catalogue["note"] or "")


def test_template_catalogue_says_why_when_unavailable(tmp_path):
    db = tmp_path / "notpl.db"
    original = dbmod.db_path()
    dbmod.set_db_path(db)
    try:
        migrate()
        config_service.invalidate()
        root = tmp_path / "plain" / "ComfyUI"
        (root / "models").mkdir(parents=True)
        (root / "main.py").write_text("#\n", encoding="utf-8")
        config_service.set_config({"comfyui_path": str(root)})
        catalogue = cs.template_catalogue()
        assert not catalogue["available"]
        assert catalogue["reason"]
    finally:
        dbmod.shutdown_writer()
        dbmod.close_thread_connections()
        dbmod.set_db_path(original)
        config_service.invalidate()


@pytest.mark.parametrize(("rel_path", "origin", "package"), [
    ("custom_nodes/ComfyUI-WanVideoWrapper/example_workflows/i2v.json",
     "bundled", "ComfyUI-WanVideoWrapper"),
    ("custom_nodes/QR/workflows/qr.json", "bundled", "QR"),
    ("user/default/workflows/mine.json", "user", None),
    ("workflows/Anime/portrait.json", "user", None),
    ("workflows/ComfyUI-LTXVideo/example_workflows/2.0/t2v.json", "user", None),
    ("solo.json", "user", None),
])
def test_workflow_origin_classification(rel_path, origin, package):
    assert workflow_origin.classify(rel_path) == (origin, package)


def test_origin_labels_read_the_way_the_requirement_words_them():
    assert workflow_origin.label("user", None) == "user"
    assert workflow_origin.label("official_template", None) == "official template"
    assert workflow_origin.label("bundled", "QR") == "bundled with QR"


def test_copied_bundles_expose_a_hint_but_stay_user_owned():
    """A graph the owner copied into their own folder is theirs; the package it
    came from is a hint, not a reclassification."""
    rel = "workflows/ComfyUI-LTXVideo/example_workflows/2.0/t2v.json"
    assert workflow_origin.classify(rel)[0] == "user"
    assert workflow_origin.example_dir_hint(rel) == "ComfyUI-LTXVideo"
