"""ComfyUI version awareness, updater discovery, and the official templates
catalogue (REQUIREMENTS_R2 C8).

Everything in here is read-only except :func:`run_updater`, which is the one
subprocess this application will ever start - and only after the caller has
confirmed the exact resolved absolute path it is about to execute.

Discovery, not assumption
-------------------------
C8.3 is explicit: find the real update mechanism for *this* install rather than
assuming a layout.  The owner's install is a portable build - ``O:\\ComfyUI`` with
``O:\\python_embeded`` and ``O:\\update\\update_comfyui.bat`` as siblings - so the
updater is neither inside the ComfyUI folder nor a plain ``git pull``.  The probe
below walks the real candidates in priority order and reports every one it found,
so the UI can show what will run before anything runs.

Version sources
---------------
``comfyui_version.py`` carries ``__version__`` and is generated by ComfyUI's own
build, so it is the authoritative installed version.  Frontend and template
package versions come from ``*.dist-info`` directory names in the interpreter
that actually launches ComfyUI, which for a portable build is ``python_embeded``
and not the interpreter this app runs under.
"""

from __future__ import annotations

import ast
import contextlib
import logging
import os
import re
import shutil
import socket
import subprocess
import threading
import time
from dataclasses import dataclass, field
from pathlib import Path

from ..core import config_service, progress
from ..core import db as dbmod
from ..core.errors import ConflictError, NotFoundError, ValidationError
from ..core.pathsafe import long_path, normalize

log = logging.getLogger(__name__)

#: ``subprocess`` above is imported for exactly one call site: the updater the
#: user has explicitly confirmed by absolute path.  Nothing else here shells out.

VERSION_FILE = "comfyui_version.py"
_VERSION_RE = re.compile(r"""__version__\s*=\s*['"]([^'"]+)['"]""")

#: Update mechanisms, most specific first.  Each entry is
#: (id, relative path from the *parent* of the ComfyUI folder, label).
PORTABLE_UPDATERS: tuple[tuple[str, str, str], ...] = (
    ("portable_stable", os.path.join("update", "update_comfyui_stable.bat"),
     "Portable updater - stable releases only"),
    ("portable", os.path.join("update", "update_comfyui.bat"),
     "Portable updater - latest master"),
    ("portable_with_deps",
     os.path.join("update", "update_comfyui_and_python_dependencies.bat"),
     "Portable updater - also reinstalls Python dependencies"),
)

#: Ports ComfyUI listens on by default.  Used only to refuse an update while it
#: looks like it is running (C8.3).
COMFYUI_PORTS = (8188, 8189)

PACKAGE_INTEREST = (
    "comfyui_frontend_package", "comfyui_workflow_templates",
    "comfyui_workflow_templates_core", "comfyui_workflow_templates_json",
    "comfyui_embedded_docs", "comfyui_manager", "comfy_config",
)

LATEST_ENDPOINTS = (
    ("github", "https://api.github.com/repos/comfyanonymous/ComfyUI/releases/latest"),
    ("pypi", "https://pypi.org/pypi/comfyui/json"),
)
LATEST_TTL_MS = 6 * 60 * 60 * 1000
NETWORK_TIMEOUT_S = 8.0

UPDATE_CHANNEL = progress.bus("comfyui_update")

_run_lock = threading.Lock()
_run_state: dict = {"status": "idle"}


# ---------------------------------------------------------------------------
# Install probe
# ---------------------------------------------------------------------------

@dataclass
class Install:
    root: Path | None = None
    parent: Path | None = None
    version: str | None = None
    version_source: str | None = None
    flavour: str = "unknown"
    flavour_reasons: list[str] = field(default_factory=list)
    python: str | None = None
    git: dict | None = None
    packages: dict = field(default_factory=dict)
    updaters: list[dict] = field(default_factory=list)


def read_version(root: Path) -> tuple[str | None, str | None]:
    """``__version__`` from ``comfyui_version.py``, parsed, never executed."""
    path = root / VERSION_FILE
    try:
        text = Path(long_path(path)).read_text(encoding="utf-8", errors="replace")
    except OSError:
        text = None
    if text:
        try:
            module = ast.parse(text)
            for node in module.body:
                if not isinstance(node, ast.Assign):
                    continue
                for target in node.targets:
                    if getattr(target, "id", None) == "__version__" and \
                            isinstance(node.value, ast.Constant):
                        return str(node.value.value), VERSION_FILE
        except (SyntaxError, ValueError):
            pass
        m = _VERSION_RE.search(text)
        if m:
            return m.group(1), VERSION_FILE

    pyproject = root / "pyproject.toml"
    try:
        raw = Path(long_path(pyproject)).read_bytes()
    except OSError:
        return None, None
    try:
        import tomllib

        data = tomllib.loads(raw.decode("utf-8", "replace"))
    except (ValueError, UnicodeDecodeError):
        return None, None
    version = ((data.get("project") or {}).get("version")
               or (data.get("tool") or {}).get("comfy", {}).get("version"))
    return (str(version), "pyproject.toml") if version else (None, None)


def _read_git(root: Path) -> dict | None:
    """Git state read as *files*.  No ``subprocess``, no network."""
    gitdir = root / ".git"
    if not gitdir.exists():
        return None
    info: dict = {"present": True, "branch": None, "commit": None,
                  "remote": None, "shallow": False, "worktree": gitdir.is_file()}
    try:
        if gitdir.is_file():
            pointer = Path(long_path(gitdir)).read_text(encoding="utf-8",
                                                        errors="replace")
            if pointer.startswith("gitdir:"):
                candidate = Path(pointer.split(":", 1)[1].strip())
                gitdir = candidate if candidate.is_absolute() else root / candidate
        head = Path(long_path(gitdir / "HEAD")).read_text(
            encoding="utf-8", errors="replace").strip()
        if head.startswith("ref:"):
            ref = head.split(":", 1)[1].strip()
            info["branch"] = ref.rsplit("/", 1)[-1]
            ref_file = gitdir / ref.replace("/", os.sep)
            if ref_file.is_file():
                info["commit"] = Path(long_path(ref_file)).read_text(
                    encoding="utf-8", errors="replace").strip()[:40]
            else:
                packed = gitdir / "packed-refs"
                if packed.is_file():
                    for line in Path(long_path(packed)).read_text(
                            encoding="utf-8", errors="replace").splitlines():
                        if line.endswith(" " + ref):
                            info["commit"] = line.split(" ", 1)[0][:40]
                            break
        else:
            info["commit"] = head[:40]
        info["shallow"] = (gitdir / "shallow").is_file()
        config = gitdir / "config"
        if config.is_file():
            text = Path(long_path(config)).read_text(encoding="utf-8",
                                                     errors="replace")
            m = re.search(r'\[remote "origin"\][^\[]*?url\s*=\s*(\S+)', text, re.S)
            if m:
                info["remote"] = m.group(1).strip()
    except OSError as exc:
        info["error"] = str(exc)[:200]
    return info


def _dist_versions(site_packages: Path) -> dict:
    """Installed distribution versions from ``*.dist-info`` directory names."""
    out: dict[str, str] = {}
    if not site_packages.is_dir():
        return out
    try:
        entries = list(os.scandir(long_path(str(site_packages))))
    except OSError:
        return out
    for entry in entries:
        name = entry.name
        if not name.endswith(".dist-info"):
            continue
        stem = name[: -len(".dist-info")]
        dist, _sep, version = stem.rpartition("-")
        if not dist or not version:
            continue
        key = dist.replace("-", "_").lower()
        if key in PACKAGE_INTEREST or key.startswith("comfyui_workflow_templates"):
            out[key] = version
    return out


def _python_home(parent: Path | None, root: Path) -> Path | None:
    """The interpreter that actually launches ComfyUI, if it ships with it."""
    for candidate in filter(None, (parent, root)):
        for name in ("python_embeded", "python_embedded", "venv", ".venv"):
            home = candidate / name
            if (home / "python.exe").is_file() or (home / "bin" / "python").is_file():
                return home
    return None


def site_packages_of(home: Path | None) -> Path | None:
    if home is None:
        return None
    for rel in (Path("Lib") / "site-packages", Path("lib") / "site-packages"):
        candidate = home / rel
        if candidate.is_dir():
            return candidate
    try:
        for entry in (home / "lib").iterdir():
            candidate = entry / "site-packages"
            if candidate.is_dir():
                return candidate
    except OSError:
        pass
    return None


def discover_updaters(root: Path, parent: Path | None, git: dict | None) -> list[dict]:
    """Every update mechanism that actually exists for THIS install (C8.3)."""
    found: list[dict] = []
    if parent is not None:
        for updater_id, rel, label in PORTABLE_UPDATERS:
            path = parent / rel
            if not path.is_file():
                continue
            found.append({
                "id": updater_id, "kind": "batch", "label": label,
                "path": str(path), "working_dir": str(path.parent),
                "command": [str(path)],
                "available": True, "recommended": updater_id == "portable",
                "note": ("Runs ComfyUI's own updater. It updates the code only; "
                         "use the '_and_python_dependencies' variant only if "
                         "dependencies are broken."),
            })
    if git and git.get("present"):
        exe = shutil.which("git")
        found.append({
            "id": "git", "kind": "git", "label": "git pull in the ComfyUI folder",
            "path": exe, "working_dir": str(root),
            "command": [exe or "git", "pull", "--ff-only"],
            "available": bool(exe), "recommended": not found,
            "note": ("Git checkout detected"
                     + (f" on branch {git.get('branch')}" if git.get("branch") else "")
                     + ("; the repository is shallow, so a fast-forward pull may "
                        "fail and the portable updater is the safer choice."
                        if git.get("shallow") else ".")),
        })
    if found and not any(f["recommended"] for f in found):
        found[0]["recommended"] = True
    return found


def _flavour(root: Path, parent: Path | None, git: dict | None,
             python_home: Path | None) -> tuple[str, list[str]]:
    reasons: list[str] = []
    portable = bool(python_home and python_home.name.startswith("python_embed"))
    if portable:
        reasons.append(f"embedded interpreter at {python_home}")
    if parent is not None and (parent / "update").is_dir():
        reasons.append(f"portable update folder at {parent / 'update'}")
        portable = True
    if parent is not None and any(parent.glob("run_*.bat")):
        reasons.append("portable launcher batch files beside the ComfyUI folder")
        portable = True
    desktop = any(marker in str(root).lower()
                  for marker in ("\\programs\\@comfyorgcomfyui", "comfyui-electron"))
    if desktop:
        reasons.append("desktop application install layout")
        return "desktop", reasons
    if portable:
        if git and git.get("present"):
            reasons.append("also a git checkout (portable builds ship one)")
        return "portable", reasons
    if git and git.get("present"):
        reasons.append(f".git present, remote {git.get('remote') or 'unknown'}")
        return "git", reasons
    reasons.append("no portable launcher, no .git")
    return "manual", reasons


def probe(cfg=None) -> Install:
    """Everything C8.1 asks for, measured from the filesystem."""
    cfg = cfg or config_service.get_config()
    root = cfg.comfyui_path
    if root is None:
        return Install()
    root = Path(normalize(root))
    parent = root.parent if root.parent != root else None
    version, source = read_version(root)
    git = _read_git(root)
    python_home = _python_home(parent, root)
    flavour, reasons = _flavour(root, parent, git, python_home)
    packages = _dist_versions(site_packages_of(python_home) or Path(""))
    return Install(
        root=root, parent=parent, version=version, version_source=source,
        flavour=flavour, flavour_reasons=reasons,
        python=str(python_home) if python_home else None,
        git=git, packages=packages,
        updaters=discover_updaters(root, parent, git),
    )


def is_running() -> dict:
    """Best-effort "is ComfyUI up right now" check (C8.3 refuses to update if so).

    A listening socket on a ComfyUI port is the signal.  It cannot prove the
    process is ComfyUI, so the answer is reported with its evidence and the UI
    says what it saw rather than asserting.
    """
    listening: list[int] = []
    for port in COMFYUI_PORTS:
        sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        sock.settimeout(0.25)
        try:
            if sock.connect_ex(("127.0.0.1", port)) == 0:
                listening.append(port)
        except OSError:
            continue
        finally:
            sock.close()
    return {
        "running": bool(listening),
        "ports": listening,
        "method": "loopback tcp probe",
        "confidence": "inferred",
        "note": ("Something is listening on "
                 + ", ".join(f"127.0.0.1:{p}" for p in listening)
                 + ". Close ComfyUI before updating."
                 if listening else "No ComfyUI port is accepting connections."),
    }


# ---------------------------------------------------------------------------
# Latest available version (read-only, offline-tolerant)
# ---------------------------------------------------------------------------

def _cache_get(key: str) -> dict | None:
    try:
        row = dbmod.one(
            dbmod.get_ro(),
            "SELECT body_json, fetched_at, expires_at, status FROM http_cache "
            "WHERE cache_key = ?", (key,))
    except Exception:  # noqa: BLE001
        return None
    if row is None or int(row["expires_at"] or 0) < dbmod.now_ms():
        return None
    import json

    try:
        return {"body": json.loads(row["body_json"] or "{}"),
                "fetched_at": int(row["fetched_at"] or 0), "cached": True}
    except ValueError:
        return None


def _cache_put(key: str, provider: str, body: dict) -> None:
    import json

    now = dbmod.now_ms()

    def _op(conn) -> None:
        conn.execute("BEGIN IMMEDIATE")
        conn.execute(
            "INSERT INTO http_cache(cache_key,provider,status,body_json,etag,"
            "fetched_at,expires_at,error) VALUES (?,?,?,?,NULL,?,?,NULL) "
            "ON CONFLICT(cache_key) DO UPDATE SET status=excluded.status, "
            "body_json=excluded.body_json, fetched_at=excluded.fetched_at, "
            "expires_at=excluded.expires_at, error=NULL",
            (key, provider, 200, json.dumps(body, default=str)[:200_000], now,
             now + LATEST_TTL_MS),
        )
        conn.commit()

    try:
        dbmod.writer().run(_op)
    except Exception as exc:  # noqa: BLE001 - a cold cache is not a failure
        log.debug("version cache write failed: %s", exc)


def _norm_version(value: str | None) -> tuple[int, ...]:
    if not value:
        return ()
    cleaned = str(value).strip().lstrip("vV")
    parts: list[int] = []
    for chunk in re.split(r"[.\-+_]", cleaned):
        if chunk.isdigit():
            parts.append(int(chunk))
        else:
            break
    return tuple(parts)


def compare_versions(installed: str | None, latest: str | None) -> str:
    a, b = _norm_version(installed), _norm_version(latest)
    if not a or not b:
        return "unknown"
    if b > a:
        return "behind"
    if b < a:
        return "ahead"
    return "current"


async def check_latest(*, force: bool = False) -> dict:
    """Look up the newest published ComfyUI release.

    Strictly read-only and strictly optional.  Offline, blocked, rate-limited and
    "online enrichment is switched off" all resolve to a plain answer with a
    reason, never an error - the Storage and Version panels must render with no
    network at all.
    """
    install = probe()
    cfg = config_service.get_config()
    base = {
        "installed": install.version,
        "installed_source": install.version_source,
        "latest": None, "state": "unknown", "checked_at": None,
        "source": None, "cached": False, "reason": None,
        "release_url": None, "release_notes": None,
    }

    if not force:
        for provider, _url in LATEST_ENDPOINTS:
            hit = _cache_get(f"comfyui:latest:{provider}")
            if hit:
                body = hit["body"]
                return {**base, "latest": body.get("version"),
                        "state": compare_versions(install.version,
                                                  body.get("version")),
                        "checked_at": hit["fetched_at"], "source": provider,
                        "cached": True, "release_url": body.get("url"),
                        "release_notes": body.get("notes"),
                        "reason": None}

    if not cfg.online_enabled:
        return {**base, "reason": "online_disabled",
                "hint": "Enable online lookups in Settings to check for updates."}

    import httpx

    last_error: str | None = None
    for provider, url in LATEST_ENDPOINTS:
        try:
            async with httpx.AsyncClient(timeout=NETWORK_TIMEOUT_S,
                                         follow_redirects=True) as client:
                response = await client.get(
                    url, headers={"Accept": "application/json",
                                  "User-Agent": "GeekatplayComfyUIAssetVault/2.0"})
            if response.status_code == 429:
                last_error = "rate_limited"
                continue
            if response.status_code >= 400:
                last_error = f"http_{response.status_code}"
                continue
            payload = response.json()
        except Exception as exc:  # noqa: BLE001 - offline is a normal state
            last_error = type(exc).__name__
            continue

        if provider == "github":
            body = {"version": str(payload.get("tag_name") or "").lstrip("vV"),
                    "url": payload.get("html_url"),
                    "notes": (payload.get("body") or "")[:4000]}
        else:
            body = {"version": str(
                (payload.get("info") or {}).get("version") or ""),
                "url": (payload.get("info") or {}).get("project_url"),
                "notes": None}
        if not body["version"]:
            last_error = "no_version_in_response"
            continue
        _cache_put(f"comfyui:latest:{provider}", provider, body)
        return {**base, "latest": body["version"],
                "state": compare_versions(install.version, body["version"]),
                "checked_at": dbmod.now_ms(), "source": provider, "cached": False,
                "release_url": body["url"], "release_notes": body["notes"],
                "reason": None}

    return {**base, "reason": last_error or "offline",
            "hint": "No network. The installed version is still shown above."}


# ---------------------------------------------------------------------------
# Official templates catalogue
# ---------------------------------------------------------------------------

TEMPLATE_PACKAGES = ("comfyui_workflow_templates_json", "comfyui_workflow_templates")


def template_catalogue(install: Install | None = None, *, limit: int = 100,
                       offset: int = 0, bundle: str | None = None,
                       q: str | None = None) -> dict:
    """The official ComfyUI templates shipped with this install (C8.4).

    These are catalogued, not indexed as vault rows, and that is deliberate: they
    live inside the Python distribution that runs ComfyUI, and making them vault
    assets would put ComfyUI's own installed files inside the reach of rename,
    move and delete.  The vault must never be able to damage the installation it
    is describing.
    """
    install = install or probe()
    site = site_packages_of(Path(install.python)) if install.python else None
    result: dict = {"available": False, "reason": None, "package_version": None,
                    "path": None, "bundles": [], "items": [], "total": 0}
    if site is None:
        result["reason"] = "no bundled interpreter found for this install"
        return result

    directory = None
    for package in TEMPLATE_PACKAGES:
        candidate = site / package / "templates"
        if candidate.is_dir():
            directory = candidate
            result["package_version"] = install.packages.get(package)
            break
    if directory is None:
        result["reason"] = "comfyui_workflow_templates is not installed"
        return result

    result["available"] = True
    result["path"] = str(directory)

    manifest = _load_manifest(site, install)
    by_id = {str(t.get("id")): t for t in manifest.get("templates", [])
             if isinstance(t, dict)}
    bundles: dict[str, int] = {}

    items: list[dict] = []
    try:
        entries = sorted(os.scandir(long_path(str(directory))), key=lambda e: e.name)
    except OSError as exc:
        result["available"] = False
        result["reason"] = str(exc)[:200]
        return result

    needle = (q or "").strip().lower()
    for entry in entries:
        if not entry.name.endswith(".json"):
            continue
        template_id = entry.name[:-5]
        meta = by_id.get(template_id) or {}
        template_bundle = str(meta.get("bundle") or "core")
        bundles[template_bundle] = bundles.get(template_bundle, 0) + 1
        if bundle and template_bundle != bundle:
            continue
        title = template_id.replace("_", " ").replace("-", " ").strip()
        if needle and needle not in template_id.lower() and needle not in title.lower():
            continue
        try:
            size = int(entry.stat().st_size)
        except OSError:
            size = 0
        items.append({
            "id": template_id, "title": title[:1].upper() + title[1:],
            "bundle": template_bundle, "filename": entry.name,
            "size": size, "path": entry.path,
            "origin": "official_template",
            "origin_label": "official template",
            "template_version": meta.get("version"),
        })

    result["bundles"] = [{"key": k, "count": v} for k, v in sorted(bundles.items())]
    result["total"] = len(items)
    result["items"] = items[offset:offset + max(1, min(500, int(limit)))]
    result["note"] = (
        "Shipped with ComfyUI itself and listed read-only. They are not indexed "
        "as vault assets, so vault file operations can never touch them."
    )
    return result


def _load_manifest(site: Path, install: Install) -> dict:
    import json

    for package in ("comfyui_workflow_templates_core", "comfyui_workflow_templates"):
        path = site / package / "manifest.json"
        if not path.is_file():
            continue
        try:
            data = json.loads(Path(long_path(path)).read_text(
                encoding="utf-8", errors="replace"))
        except (OSError, ValueError):
            continue
        if isinstance(data, dict):
            data.setdefault("_package", package)
            data.setdefault("_version", install.packages.get(package))
            return data
    return {}


# ---------------------------------------------------------------------------
# Running the updater
# ---------------------------------------------------------------------------

MAX_OUTPUT_LINES = 4000
UPDATE_TIMEOUT_S = 30 * 60


def resolve_updater(updater_id: str | None = None, cfg=None) -> dict:
    install = probe(cfg)
    if not install.updaters:
        raise NotFoundError(
            "No update mechanism was found for this ComfyUI installation.",
            details={"comfyui_path": str(install.root) if install.root else None,
                     "flavour": install.flavour,
                     "hint": "A portable build keeps update_comfyui.bat in an "
                             "'update' folder beside the ComfyUI folder."},
        )
    if updater_id:
        for entry in install.updaters:
            if entry["id"] == updater_id:
                chosen = entry
                break
        else:
            raise NotFoundError(
                f"'{updater_id}' is not an updater this install offers.",
                details={"available": [e["id"] for e in install.updaters]})
    else:
        chosen = next(e for e in install.updaters if e["recommended"])
    if not chosen.get("available"):
        raise ConflictError(
            f"{chosen['label']} was found but cannot be run.",
            details={"updater": chosen["id"], "path": chosen.get("path")})
    return chosen


def update_status() -> dict:
    state = dict(_run_state)
    state["running"] = state.get("status") == "running"
    return state


def run_updater(updater_id: str | None, *, confirm_path: str,
                trigger: str = "api") -> dict:
    """Run the discovered updater.  The one subprocess this app ever starts.

    ``confirm_path`` must equal the resolved absolute path of the chosen updater.
    That is not ceremony: it is what makes the confirmation dialog's promise -
    "this exact file will be executed" - structurally true, and it means a
    stale UI or a mistaken MCP call cannot run something the user never saw.
    """
    chosen = resolve_updater(updater_id)
    resolved = str(normalize(chosen["path"])) if chosen.get("path") else ""
    if not confirm_path or str(normalize(confirm_path)) != resolved:
        raise ValidationError(
            "The update was not confirmed for the path that would actually run.",
            details={"resolved_path": resolved, "confirm_path": confirm_path,
                     "hint": "Send confirm_path exactly as returned by "
                             "GET /api/v1/comfyui/update/plan."},
        )
    running = is_running()
    if running["running"]:
        raise ConflictError(
            "ComfyUI appears to be running. Close it before updating.",
            details=running)

    with _run_lock:
        if _run_state.get("status") == "running":
            raise ConflictError("An update is already running.",
                                details={"started_at": _run_state.get("started_at")})
        _run_state.clear()
        _run_state.update({
            "status": "running", "updater": chosen["id"], "path": resolved,
            "command": chosen["command"], "started_at": dbmod.now_ms(),
            "trigger": trigger, "lines": 0, "exit_code": None,
        })

    thread = threading.Thread(target=_run_updater_thread,
                              args=(chosen, resolved), daemon=True,
                              name="comfyui-update")
    thread.start()
    UPDATE_CHANNEL.publish("phase", {"phase": "starting", "updater": chosen["id"],
                                     "path": resolved})
    return {
        "started": True, "updater": chosen["id"], "label": chosen["label"],
        "path": resolved, "working_dir": chosen["working_dir"],
        "stream": "/api/v1/comfyui/update/stream",
        "started_at": _run_state["started_at"],
    }


def _run_updater_thread(chosen: dict, resolved: str) -> None:
    started = time.perf_counter()
    lines = 0
    exit_code: int | None = None
    error: str | None = None
    try:
        # A list argv with shell=False: nothing here is ever assembled from user
        # text, and the executable is one of the paths `discover_updaters` found
        # on disk.
        proc = subprocess.Popen(  # noqa: S603
            list(chosen["command"]),
            cwd=chosen.get("working_dir") or None,
            stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
            stdin=subprocess.DEVNULL, text=True, encoding="utf-8",
            errors="replace", bufsize=1,
            creationflags=getattr(subprocess, "CREATE_NO_WINDOW", 0),
        )
    except OSError as exc:
        error = str(exc)[:400]
        UPDATE_CHANNEL.publish("error", {"message": error})
    else:
        assert proc.stdout is not None
        try:
            for raw in proc.stdout:
                line = raw.rstrip("\r\n")
                lines += 1
                if lines <= MAX_OUTPUT_LINES:
                    UPDATE_CHANNEL.publish("output", {"line": line[:2000],
                                                      "n": lines})
                elif lines == MAX_OUTPUT_LINES + 1:
                    UPDATE_CHANNEL.publish(
                        "output", {"line": "... output truncated ...", "n": lines})
                _run_state["lines"] = lines
                if time.perf_counter() - started > UPDATE_TIMEOUT_S:
                    proc.kill()
                    error = "The updater exceeded its time limit and was stopped."
                    break
            exit_code = proc.wait(timeout=60)
        except Exception as exc:  # noqa: BLE001 - reported, never raised into a thread
            error = str(exc)[:400]
            with contextlib.suppress(OSError, ValueError):
                proc.kill()

    duration = int((time.perf_counter() - started) * 1000)
    after = probe()
    payload = {
        "status": "completed" if exit_code == 0 and not error else "failed",
        "updater": chosen["id"], "path": resolved, "exit_code": exit_code,
        "error": error, "duration_ms": duration, "lines": lines,
        "version_after": after.version,
        "finished_at": dbmod.now_ms(),
        "restart_required": True,
        "note": ("ComfyUI was updated. Restart ComfyUI, then re-scan the vault "
                 "so new bundled workflows and node classes are picked up."),
    }
    with _run_lock:
        _run_state.update(payload)
        _run_state["running"] = False
    UPDATE_CHANNEL.publish("done", payload)


# ---------------------------------------------------------------------------
# Report shaping
# ---------------------------------------------------------------------------

def report(cfg=None) -> dict:
    """The read-only C8 panel payload."""
    install = probe(cfg)
    if install.root is None:
        return {"configured": False, "comfyui_path": None, "version": None,
                "flavour": "unknown", "updaters": [], "packages": {},
                "running": {"running": False, "ports": []}}
    return {
        "configured": True,
        "comfyui_path": str(install.root),
        "install_parent": str(install.parent) if install.parent else None,
        "version": install.version,
        "version_source": install.version_source,
        "flavour": install.flavour,
        "flavour_evidence": install.flavour_reasons,
        "python_home": install.python,
        "git": install.git,
        "packages": install.packages,
        "updaters": install.updaters,
        "recommended_updater": next(
            (u["id"] for u in install.updaters if u["recommended"]), None),
        "running": is_running(),
        "update_status": update_status(),
    }
