"""ComfyUI version awareness, updater discovery, the official templates
catalogue, and opening a workflow inside ComfyUI (REQUIREMENTS_R2 C8).

Everything in here is read-only except three functions:
:func:`run_updater` and :func:`start_comfyui`, the only two places this
application ever starts a process, and :func:`copy_into_user_workflows`, the
only place it ever writes into the ComfyUI installation.  Each runs only after
the caller has confirmed the exact resolved absolute path it will act on.

Discovery, not assumption
-------------------------
C8.3 is explicit: find the real update mechanism for *this* install rather than
assuming a layout.  The owner's install is a portable build - ``O:\\ComfyUI`` with
``O:\\python_embeded`` and ``O:\\update\\update_comfyui.bat`` as siblings - so the
updater is neither inside the ComfyUI folder nor a plain ``git pull``.  The probe
below walks the real candidates in priority order and reports every one it found,
so the UI can show what will run before anything runs.

Version sources
---------------
``comfyui_version.py`` carries ``__version__`` and is generated by ComfyUI's own
build, so it is the authoritative installed version.  Frontend and template
package versions come from ``*.dist-info`` directory names in the interpreter
that actually launches ComfyUI, which for a portable build is ``python_embeded``
and not the interpreter this app runs under.
"""

from __future__ import annotations

import ast
import contextlib
import logging
import os
import re
import shutil
import socket
import subprocess
import threading
import time
from dataclasses import dataclass, field
from pathlib import Path

from ..core import config_service, progress
from ..core import db as dbmod
from ..core.errors import ConflictError, NotFoundError, ValidationError
from ..core.pathsafe import (
    is_contained,
    long_path,
    normalize,
    resolve_within_roots,
    validate_filename,
)

log = logging.getLogger(__name__)

#: ``subprocess`` above is imported for exactly two call sites: the updater and
#: the ComfyUI launcher, each of which the user has explicitly confirmed by
#: absolute path.  Nothing else in this module shells out, and both argv vectors
#: come from on-disk discovery - never from anything a caller typed.  Both are
#: also checked by :func:`cmd_line_hazard` first, because a ``.bat`` argv is not
#: opaque on Windows (SECURITY_REVIEW S-19).

VERSION_FILE = "comfyui_version.py"
_VERSION_RE = re.compile(r"""__version__\s*=\s*['"]([^'"]+)['"]""")

#: Update mechanisms, most specific first.  Each entry is
#: (id, relative path from the *parent* of the ComfyUI folder, label).
PORTABLE_UPDATERS: tuple[tuple[str, str, str], ...] = (
    ("portable_stable", os.path.join("update", "update_comfyui_stable.bat"),
     "Portable updater - stable releases only"),
    ("portable", os.path.join("update", "update_comfyui.bat"),
     "Portable updater - latest master"),
    ("portable_with_deps",
     os.path.join("update", "update_comfyui_and_python_dependencies.bat"),
     "Portable updater - also reinstalls Python dependencies"),
)

#: Ports ComfyUI listens on by default.  Used only to refuse an update while it
#: looks like it is running (C8.3).
COMFYUI_PORTS = (8188, 8189)

#: Files a real ComfyUI checkout or portable build always carries.
#: ``comfyui_version.py`` is generated by ComfyUI's own release process, so a
#: directory that merely holds ``models/`` plus ``main.py`` - which is all
#: ``PATCH /system/config`` requires - does not get it for free.  SECURITY_REVIEW
#: S-04 raised this bar for the updater; S-20 raises it for the launcher, which
#: nominates an executable from the same caller-settable ``comfyui_path``.
INSTALL_PROOF = ("comfyui_version.py", "main.py")


def missing_install_proof(root: Path | None) -> list[str]:
    """What a candidate folder lacks before it may nominate an executable.

    Empty means "this is a real install".  The order and the names are part of
    the API: the updater routes report them as ``details.missing``.
    """
    if root is None or not Path(long_path(root)).is_dir():
        return ["comfyui_path"]
    missing = [name for name in INSTALL_PROOF if not (root / name).is_file()]
    if not (root / "models").is_dir():
        missing.append("models")
    return missing


#: Characters ``cmd.exe`` acts on even when it is handed a command line that was
#: built as a list argv.  SECURITY_REVIEW S-19: a ``.bat``/``.cmd`` target is
#: never executed directly on Windows - ``CreateProcess`` runs it through
#: ``cmd.exe``, which re-parses the *whole* command line - so "list argv,
#: shell=False" does not by itself make the executable's own path an opaque
#: single argument.  ``list2cmdline`` quotes a token only when it contains a
#: space or a tab, so a metacharacter in an otherwise space-free path is live.
#: ``"`` and ``%`` survive quoting; the rest do not.
CMD_UNSAFE_ALWAYS = '"%'
CMD_UNSAFE_UNQUOTED = '&|<>^()!'


def cmd_line_hazard(command) -> str | None:
    """The character ``cmd.exe`` would act on in this argv, or ``None``.

    Only ``.bat``/``.cmd`` targets are affected: everything else is handed to
    ``CreateProcess`` as a real executable and no command interpreter sees it.
    """
    argv = [str(a) for a in (command or [])]
    if not argv:
        return None
    exe = argv[0]
    if not exe.lower().endswith((".bat", ".cmd")):
        return None
    quoted = subprocess.list2cmdline(argv).startswith('"')
    for ch in exe:
        if ch in CMD_UNSAFE_ALWAYS:
            return ch
        if ch in CMD_UNSAFE_UNQUOTED and not quoted:
            return ch
    return None


def _mark_cmd_hazard(entry: dict) -> dict:
    """Refuse an entry whose own path would be re-parsed by ``cmd.exe``."""
    hazard = cmd_line_hazard(entry.get("command"))
    if hazard is not None:
        entry["available"] = False
        entry["unsafe_reason"] = "cmd_metacharacter_in_path"
        entry["note"] = (
            f"Refused: the path contains '{hazard}', which cmd.exe would treat "
            "as syntax rather than as part of the filename when it runs a batch "
            "file. Rename it, or start ComfyUI yourself.")
    return entry

PACKAGE_INTEREST = (
    "comfyui_frontend_package", "comfyui_workflow_templates",
    "comfyui_workflow_templates_core", "comfyui_workflow_templates_json",
    "comfyui_embedded_docs", "comfyui_manager", "comfy_config",
)

LATEST_ENDPOINTS = (
    ("github", "https://api.github.com/repos/comfyanonymous/ComfyUI/releases/latest"),
    ("pypi", "https://pypi.org/pypi/comfyui/json"),
)
LATEST_TTL_MS = 6 * 60 * 60 * 1000
NETWORK_TIMEOUT_S = 8.0

UPDATE_CHANNEL = progress.bus("comfyui_update")

_run_lock = threading.Lock()
_run_state: dict = {"status": "idle"}


# ---------------------------------------------------------------------------
# Install probe
# ---------------------------------------------------------------------------

@dataclass
class Install:
    root: Path | None = None
    parent: Path | None = None
    version: str | None = None
    version_source: str | None = None
    flavour: str = "unknown"
    flavour_reasons: list[str] = field(default_factory=list)
    python: str | None = None
    git: dict | None = None
    packages: dict = field(default_factory=dict)
    updaters: list[dict] = field(default_factory=list)
    launchers: list[dict] = field(default_factory=list)


def read_version(root: Path) -> tuple[str | None, str | None]:
    """``__version__`` from ``comfyui_version.py``, parsed, never executed."""
    path = root / VERSION_FILE
    try:
        text = Path(long_path(path)).read_text(encoding="utf-8", errors="replace")
    except OSError:
        text = None
    if text:
        try:
            module = ast.parse(text)
            for node in module.body:
                if not isinstance(node, ast.Assign):
                    continue
                for target in node.targets:
                    if getattr(target, "id", None) == "__version__" and \
                            isinstance(node.value, ast.Constant):
                        return str(node.value.value), VERSION_FILE
        except (SyntaxError, ValueError):
            pass
        m = _VERSION_RE.search(text)
        if m:
            return m.group(1), VERSION_FILE

    pyproject = root / "pyproject.toml"
    try:
        raw = Path(long_path(pyproject)).read_bytes()
    except OSError:
        return None, None
    try:
        import tomllib

        data = tomllib.loads(raw.decode("utf-8", "replace"))
    except (ValueError, UnicodeDecodeError):
        return None, None
    version = ((data.get("project") or {}).get("version")
               or (data.get("tool") or {}).get("comfy", {}).get("version"))
    return (str(version), "pyproject.toml") if version else (None, None)


def _read_git(root: Path) -> dict | None:
    """Git state read as *files*.  No ``subprocess``, no network."""
    gitdir = root / ".git"
    if not gitdir.exists():
        return None
    info: dict = {"present": True, "branch": None, "commit": None,
                  "remote": None, "shallow": False, "worktree": gitdir.is_file()}
    try:
        if gitdir.is_file():
            pointer = Path(long_path(gitdir)).read_text(encoding="utf-8",
                                                        errors="replace")
            if pointer.startswith("gitdir:"):
                candidate = Path(pointer.split(":", 1)[1].strip())
                gitdir = candidate if candidate.is_absolute() else root / candidate
        head = Path(long_path(gitdir / "HEAD")).read_text(
            encoding="utf-8", errors="replace").strip()
        if head.startswith("ref:"):
            ref = head.split(":", 1)[1].strip()
            info["branch"] = ref.rsplit("/", 1)[-1]
            ref_file = gitdir / ref.replace("/", os.sep)
            if ref_file.is_file():
                info["commit"] = Path(long_path(ref_file)).read_text(
                    encoding="utf-8", errors="replace").strip()[:40]
            else:
                packed = gitdir / "packed-refs"
                if packed.is_file():
                    for line in Path(long_path(packed)).read_text(
                            encoding="utf-8", errors="replace").splitlines():
                        if line.endswith(" " + ref):
                            info["commit"] = line.split(" ", 1)[0][:40]
                            break
        else:
            info["commit"] = head[:40]
        info["shallow"] = (gitdir / "shallow").is_file()
        config = gitdir / "config"
        if config.is_file():
            text = Path(long_path(config)).read_text(encoding="utf-8",
                                                     errors="replace")
            m = re.search(r'\[remote "origin"\][^\[]*?url\s*=\s*(\S+)', text, re.S)
            if m:
                info["remote"] = m.group(1).strip()
    except OSError as exc:
        info["error"] = str(exc)[:200]
    return info


def _dist_versions(site_packages: Path) -> dict:
    """Installed distribution versions from ``*.dist-info`` directory names."""
    out: dict[str, str] = {}
    if not site_packages.is_dir():
        return out
    try:
        entries = list(os.scandir(long_path(str(site_packages))))
    except OSError:
        return out
    for entry in entries:
        name = entry.name
        if not name.endswith(".dist-info"):
            continue
        stem = name[: -len(".dist-info")]
        dist, _sep, version = stem.rpartition("-")
        if not dist or not version:
            continue
        key = dist.replace("-", "_").lower()
        if key in PACKAGE_INTEREST or key.startswith("comfyui_workflow_templates"):
            out[key] = version
    return out


def _python_home(parent: Path | None, root: Path) -> Path | None:
    """The interpreter that actually launches ComfyUI, if it ships with it."""
    for candidate in filter(None, (parent, root)):
        for name in ("python_embeded", "python_embedded", "venv", ".venv"):
            home = candidate / name
            if (home / "python.exe").is_file() or (home / "bin" / "python").is_file():
                return home
    return None


def site_packages_of(home: Path | None) -> Path | None:
    if home is None:
        return None
    for rel in (Path("Lib") / "site-packages", Path("lib") / "site-packages"):
        candidate = home / rel
        if candidate.is_dir():
            return candidate
    try:
        for entry in (home / "lib").iterdir():
            candidate = entry / "site-packages"
            if candidate.is_dir():
                return candidate
    except OSError:
        pass
    return None


def discover_updaters(root: Path, parent: Path | None, git: dict | None) -> list[dict]:
    """Every update mechanism that actually exists for THIS install (C8.3)."""
    found: list[dict] = []
    if parent is not None:
        for updater_id, rel, label in PORTABLE_UPDATERS:
            path = parent / rel
            if not path.is_file():
                continue
            found.append(_mark_cmd_hazard({
                "id": updater_id, "kind": "batch", "label": label,
                "path": str(path), "working_dir": str(path.parent),
                "command": [str(path)],
                "available": True, "recommended": updater_id == "portable",
                "note": ("Runs ComfyUI's own updater. It updates the code only; "
                         "use the '_and_python_dependencies' variant only if "
                         "dependencies are broken."),
            }))
    if git and git.get("present"):
        exe = shutil.which("git")
        found.append({
            "id": "git", "kind": "git", "label": "git pull in the ComfyUI folder",
            "path": exe, "working_dir": str(root),
            "command": [exe or "git", "pull", "--ff-only"],
            "available": bool(exe), "recommended": not found,
            "note": ("Git checkout detected"
                     + (f" on branch {git.get('branch')}" if git.get("branch") else "")
                     + ("; the repository is shallow, so a fast-forward pull may "
                        "fail and the portable updater is the safer choice."
                        if git.get("shallow") else ".")),
        })
    for entry in found:
        if not entry.get("available"):
            entry["recommended"] = False
    usable = [f for f in found if f.get("available")]
    if usable and not any(f["recommended"] for f in usable):
        usable[0]["recommended"] = True
    return found


def _flavour(root: Path, parent: Path | None, git: dict | None,
             python_home: Path | None) -> tuple[str, list[str]]:
    reasons: list[str] = []
    portable = bool(python_home and python_home.name.startswith("python_embed"))
    if portable:
        reasons.append(f"embedded interpreter at {python_home}")
    if parent is not None and (parent / "update").is_dir():
        reasons.append(f"portable update folder at {parent / 'update'}")
        portable = True
    if parent is not None and any(parent.glob("run_*.bat")):
        reasons.append("portable launcher batch files beside the ComfyUI folder")
        portable = True
    desktop = any(marker in str(root).lower()
                  for marker in ("\\programs\\@comfyorgcomfyui", "comfyui-electron"))
    if desktop:
        reasons.append("desktop application install layout")
        return "desktop", reasons
    if portable:
        if git and git.get("present"):
            reasons.append("also a git checkout (portable builds ship one)")
        return "portable", reasons
    if git and git.get("present"):
        reasons.append(f".git present, remote {git.get('remote') or 'unknown'}")
        return "git", reasons
    reasons.append("no portable launcher, no .git")
    return "manual", reasons


def probe(cfg=None) -> Install:
    """Everything C8.1 asks for, measured from the filesystem."""
    cfg = cfg or config_service.get_config()
    root = cfg.comfyui_path
    if root is None:
        return Install()
    root = Path(normalize(root))
    parent = root.parent if root.parent != root else None
    version, source = read_version(root)
    git = _read_git(root)
    python_home = _python_home(parent, root)
    flavour, reasons = _flavour(root, parent, git, python_home)
    packages = _dist_versions(site_packages_of(python_home) or Path(""))
    return Install(
        root=root, parent=parent, version=version, version_source=source,
        flavour=flavour, flavour_reasons=reasons,
        python=str(python_home) if python_home else None,
        git=git, packages=packages,
        updaters=discover_updaters(root, parent, git),
        launchers=discover_launchers(root, parent, python_home),
    )


def is_running() -> dict:
    """Best-effort "is ComfyUI up right now" check (C8.3 refuses to update if so).

    A listening socket on a ComfyUI port is the signal.  It cannot prove the
    process is ComfyUI, so the answer is reported with its evidence and the UI
    says what it saw rather than asserting.
    """
    listening: list[int] = []
    for port in COMFYUI_PORTS:
        sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        sock.settimeout(0.25)
        try:
            if sock.connect_ex(("127.0.0.1", port)) == 0:
                listening.append(port)
        except OSError:
            continue
        finally:
            sock.close()
    return {
        "running": bool(listening),
        "ports": listening,
        "method": "loopback tcp probe",
        "confidence": "inferred",
        "note": ("Something is listening on "
                 + ", ".join(f"127.0.0.1:{p}" for p in listening)
                 + ". Close ComfyUI before updating."
                 if listening else "No ComfyUI port is accepting connections."),
    }


# ---------------------------------------------------------------------------
# Latest available version (read-only, offline-tolerant)
# ---------------------------------------------------------------------------

def _cache_get(key: str) -> dict | None:
    try:
        row = dbmod.one(
            dbmod.get_ro(),
            "SELECT body_json, fetched_at, expires_at, status FROM http_cache "
            "WHERE cache_key = ?", (key,))
    except Exception:  # noqa: BLE001
        return None
    if row is None or int(row["expires_at"] or 0) < dbmod.now_ms():
        return None
    import json

    try:
        return {"body": json.loads(row["body_json"] or "{}"),
                "fetched_at": int(row["fetched_at"] or 0), "cached": True}
    except ValueError:
        return None


def _cache_put(key: str, provider: str, body: dict) -> None:
    import json

    now = dbmod.now_ms()

    def _op(conn) -> None:
        conn.execute("BEGIN IMMEDIATE")
        conn.execute(
            "INSERT INTO http_cache(cache_key,provider,status,body_json,etag,"
            "fetched_at,expires_at,error) VALUES (?,?,?,?,NULL,?,?,NULL) "
            "ON CONFLICT(cache_key) DO UPDATE SET status=excluded.status, "
            "body_json=excluded.body_json, fetched_at=excluded.fetched_at, "
            "expires_at=excluded.expires_at, error=NULL",
            (key, provider, 200, json.dumps(body, default=str)[:200_000], now,
             now + LATEST_TTL_MS),
        )
        conn.commit()

    try:
        dbmod.writer().run(_op)
    except Exception as exc:  # noqa: BLE001 - a cold cache is not a failure
        log.debug("version cache write failed: %s", exc)


def _norm_version(value: str | None) -> tuple[int, ...]:
    if not value:
        return ()
    cleaned = str(value).strip().lstrip("vV")
    parts: list[int] = []
    for chunk in re.split(r"[.\-+_]", cleaned):
        if chunk.isdigit():
            parts.append(int(chunk))
        else:
            break
    return tuple(parts)


def compare_versions(installed: str | None, latest: str | None) -> str:
    a, b = _norm_version(installed), _norm_version(latest)
    if not a or not b:
        return "unknown"
    if b > a:
        return "behind"
    if b < a:
        return "ahead"
    return "current"


async def check_latest(*, force: bool = False) -> dict:
    """Look up the newest published ComfyUI release.

    Strictly read-only and strictly optional.  Offline, blocked, rate-limited and
    "online enrichment is switched off" all resolve to a plain answer with a
    reason, never an error - the Storage and Version panels must render with no
    network at all.
    """
    install = probe()
    cfg = config_service.get_config()
    base = {
        "installed": install.version,
        "installed_source": install.version_source,
        "latest": None, "state": "unknown", "checked_at": None,
        "source": None, "cached": False, "reason": None,
        "release_url": None, "release_notes": None,
    }

    if not force:
        for provider, _url in LATEST_ENDPOINTS:
            hit = _cache_get(f"comfyui:latest:{provider}")
            if hit:
                body = hit["body"]
                return {**base, "latest": body.get("version"),
                        "state": compare_versions(install.version,
                                                  body.get("version")),
                        "checked_at": hit["fetched_at"], "source": provider,
                        "cached": True, "release_url": body.get("url"),
                        "release_notes": body.get("notes"),
                        "reason": None}

    if not cfg.online_enabled:
        return {**base, "reason": "online_disabled",
                "hint": "Enable online lookups in Settings to check for updates."}

    import httpx

    last_error: str | None = None
    for provider, url in LATEST_ENDPOINTS:
        try:
            async with httpx.AsyncClient(timeout=NETWORK_TIMEOUT_S,
                                         follow_redirects=True) as client:
                response = await client.get(
                    url, headers={"Accept": "application/json",
                                  "User-Agent": "GeekatplayComfyUIAssetVault/2.0"})
            if response.status_code == 429:
                last_error = "rate_limited"
                continue
            if response.status_code >= 400:
                last_error = f"http_{response.status_code}"
                continue
            payload = response.json()
        except Exception as exc:  # noqa: BLE001 - offline is a normal state
            last_error = type(exc).__name__
            continue

        if provider == "github":
            body = {"version": str(payload.get("tag_name") or "").lstrip("vV"),
                    "url": payload.get("html_url"),
                    "notes": (payload.get("body") or "")[:4000]}
        else:
            body = {"version": str(
                (payload.get("info") or {}).get("version") or ""),
                "url": (payload.get("info") or {}).get("project_url"),
                "notes": None}
        if not body["version"]:
            last_error = "no_version_in_response"
            continue
        _cache_put(f"comfyui:latest:{provider}", provider, body)
        return {**base, "latest": body["version"],
                "state": compare_versions(install.version, body["version"]),
                "checked_at": dbmod.now_ms(), "source": provider, "cached": False,
                "release_url": body["url"], "release_notes": body["notes"],
                "reason": None}

    return {**base, "reason": last_error or "offline",
            "hint": "No network. The installed version is still shown above."}


# ---------------------------------------------------------------------------
# Official templates catalogue
# ---------------------------------------------------------------------------

TEMPLATE_PACKAGES = ("comfyui_workflow_templates_json", "comfyui_workflow_templates")


def template_catalogue(install: Install | None = None, *, limit: int = 100,
                       offset: int = 0, bundle: str | None = None,
                       q: str | None = None) -> dict:
    """The official ComfyUI templates shipped with this install (C8.4).

    These are catalogued, not indexed as vault rows, and that is deliberate: they
    live inside the Python distribution that runs ComfyUI, and making them vault
    assets would put ComfyUI's own installed files inside the reach of rename,
    move and delete.  The vault must never be able to damage the installation it
    is describing.
    """
    install = install or probe()
    site = site_packages_of(Path(install.python)) if install.python else None
    result: dict = {"available": False, "reason": None, "package_version": None,
                    "path": None, "bundles": [], "items": [], "total": 0}
    if site is None:
        result["reason"] = "no bundled interpreter found for this install"
        return result

    directory = None
    for package in TEMPLATE_PACKAGES:
        candidate = site / package / "templates"
        if candidate.is_dir():
            directory = candidate
            result["package_version"] = install.packages.get(package)
            break
    if directory is None:
        result["reason"] = "comfyui_workflow_templates is not installed"
        return result

    result["available"] = True
    result["path"] = str(directory)

    manifest = _load_manifest(site, install)
    by_id = {str(t.get("id")): t for t in manifest.get("templates", [])
             if isinstance(t, dict)}
    bundles: dict[str, int] = {}

    items: list[dict] = []
    try:
        entries = sorted(os.scandir(long_path(str(directory))), key=lambda e: e.name)
    except OSError as exc:
        result["available"] = False
        result["reason"] = str(exc)[:200]
        return result

    needle = (q or "").strip().lower()
    for entry in entries:
        if not entry.name.endswith(".json"):
            continue
        template_id = entry.name[:-5]
        meta = by_id.get(template_id) or {}
        template_bundle = str(meta.get("bundle") or "core")
        bundles[template_bundle] = bundles.get(template_bundle, 0) + 1
        if bundle and template_bundle != bundle:
            continue
        title = template_id.replace("_", " ").replace("-", " ").strip()
        if needle and needle not in template_id.lower() and needle not in title.lower():
            continue
        try:
            size = int(entry.stat().st_size)
        except OSError:
            size = 0
        items.append({
            "id": template_id, "title": title[:1].upper() + title[1:],
            "bundle": template_bundle, "filename": entry.name,
            "size": size, "path": entry.path,
            "origin": "official_template",
            "origin_label": "official template",
            "template_version": meta.get("version"),
        })

    result["bundles"] = [{"key": k, "count": v} for k, v in sorted(bundles.items())]
    result["total"] = len(items)
    result["items"] = items[offset:offset + max(1, min(500, int(limit)))]
    result["note"] = (
        "Shipped with ComfyUI itself and listed read-only. They are not indexed "
        "as vault assets, so vault file operations can never touch them."
    )
    return result


def _load_manifest(site: Path, install: Install) -> dict:
    import json

    for package in ("comfyui_workflow_templates_core", "comfyui_workflow_templates"):
        path = site / package / "manifest.json"
        if not path.is_file():
            continue
        try:
            data = json.loads(Path(long_path(path)).read_text(
                encoding="utf-8", errors="replace"))
        except (OSError, ValueError):
            continue
        if isinstance(data, dict):
            data.setdefault("_package", package)
            data.setdefault("_version", install.packages.get(package))
            return data
    return {}


# ---------------------------------------------------------------------------
# Running the updater
# ---------------------------------------------------------------------------

MAX_OUTPUT_LINES = 4000
UPDATE_TIMEOUT_S = 30 * 60


def resolve_updater(updater_id: str | None = None, cfg=None) -> dict:
    install = probe(cfg)
    if not install.updaters:
        raise NotFoundError(
            "No update mechanism was found for this ComfyUI installation.",
            details={"comfyui_path": str(install.root) if install.root else None,
                     "flavour": install.flavour,
                     "hint": "A portable build keeps update_comfyui.bat in an "
                             "'update' folder beside the ComfyUI folder."},
        )
    if updater_id:
        for entry in install.updaters:
            if entry["id"] == updater_id:
                chosen = entry
                break
        else:
            raise NotFoundError(
                f"'{updater_id}' is not an updater this install offers.",
                details={"available": [e["id"] for e in install.updaters]})
    else:
        chosen = next((e for e in install.updaters if e["recommended"]),
                      install.updaters[0])
    if not chosen.get("available"):
        raise ConflictError(
            f"{chosen['label']} was found but cannot be run.",
            details={"updater": chosen["id"], "path": chosen.get("path")})
    return chosen


def _refuse_a_reparsed_command(chosen: dict) -> None:
    """SECURITY_REVIEW S-19, checked where the argv is about to be used.

    ``discover_*`` already marks such an entry unavailable.  This is the same
    check at the choke point, because the value reaching ``Popen`` is what
    matters - not the value that was inspected a moment earlier.
    """
    hazard = cmd_line_hazard(chosen.get("command"))
    if hazard is None:
        return
    raise ConflictError(
        "That path cannot be run safely: cmd.exe would read the character "
        f"'{hazard}' in it as syntax rather than as part of the filename, so "
        "more than the confirmed file could run. Rename it, or start it "
        "yourself.",
        details={"path": chosen.get("path"), "character": hazard,
                 "reason": "cmd_metacharacter_in_path"})


def update_status() -> dict:
    state = dict(_run_state)
    state["running"] = state.get("status") == "running"
    return state


def run_updater(updater_id: str | None, *, confirm_path: str,
                trigger: str = "api") -> dict:
    """Run the discovered updater.  The one subprocess this app ever starts.

    ``confirm_path`` must equal the resolved absolute path of the chosen updater.
    That is not ceremony: it is what makes the confirmation dialog's promise -
    "this exact file will be executed" - structurally true, and it means a
    stale UI or a mistaken MCP call cannot run something the user never saw.
    """
    chosen = resolve_updater(updater_id)
    resolved = str(normalize(chosen["path"])) if chosen.get("path") else ""
    if not confirm_path or str(normalize(confirm_path)) != resolved:
        raise ValidationError(
            "The update was not confirmed for the path that would actually run.",
            details={"resolved_path": resolved, "confirm_path": confirm_path,
                     "hint": "Send confirm_path exactly as returned by "
                             "GET /api/v1/comfyui/update/plan."},
        )
    _refuse_a_reparsed_command(chosen)
    running = is_running()
    if running["running"]:
        raise ConflictError(
            "ComfyUI appears to be running. Close it before updating.",
            details=running)

    with _run_lock:
        if _run_state.get("status") == "running":
            raise ConflictError("An update is already running.",
                                details={"started_at": _run_state.get("started_at")})
        _run_state.clear()
        _run_state.update({
            "status": "running", "updater": chosen["id"], "path": resolved,
            "command": chosen["command"], "started_at": dbmod.now_ms(),
            "trigger": trigger, "lines": 0, "exit_code": None,
        })

    thread = threading.Thread(target=_run_updater_thread,
                              args=(chosen, resolved), daemon=True,
                              name="comfyui-update")
    thread.start()
    UPDATE_CHANNEL.publish("phase", {"phase": "starting", "updater": chosen["id"],
                                     "path": resolved})
    return {
        "started": True, "updater": chosen["id"], "label": chosen["label"],
        "path": resolved, "working_dir": chosen["working_dir"],
        "stream": "/api/v1/comfyui/update/stream",
        "started_at": _run_state["started_at"],
    }


def _run_updater_thread(chosen: dict, resolved: str) -> None:
    started = time.perf_counter()
    lines = 0
    exit_code: int | None = None
    error: str | None = None
    try:
        # A list argv with shell=False: nothing here is ever assembled from user
        # text, and the executable is one of the paths `discover_updaters` found
        # on disk.  The three filenames are fixed literals, but the directory
        # above them is not, so `cmd_line_hazard` has already refused a path
        # cmd.exe would re-parse (SECURITY_REVIEW S-19).
        proc = subprocess.Popen(  # noqa: S603
            list(chosen["command"]),
            cwd=chosen.get("working_dir") or None,
            stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
            stdin=subprocess.DEVNULL, text=True, encoding="utf-8",
            errors="replace", bufsize=1,
            creationflags=getattr(subprocess, "CREATE_NO_WINDOW", 0),
        )
    except OSError as exc:
        error = str(exc)[:400]
        UPDATE_CHANNEL.publish("error", {"message": error})
    else:
        assert proc.stdout is not None
        try:
            for raw in proc.stdout:
                line = raw.rstrip("\r\n")
                lines += 1
                if lines <= MAX_OUTPUT_LINES:
                    UPDATE_CHANNEL.publish("output", {"line": line[:2000],
                                                      "n": lines})
                elif lines == MAX_OUTPUT_LINES + 1:
                    UPDATE_CHANNEL.publish(
                        "output", {"line": "... output truncated ...", "n": lines})
                _run_state["lines"] = lines
                if time.perf_counter() - started > UPDATE_TIMEOUT_S:
                    proc.kill()
                    error = "The updater exceeded its time limit and was stopped."
                    break
            exit_code = proc.wait(timeout=60)
        except Exception as exc:  # noqa: BLE001 - reported, never raised into a thread
            error = str(exc)[:400]
            with contextlib.suppress(OSError, ValueError):
                proc.kill()

    duration = int((time.perf_counter() - started) * 1000)
    after = probe()
    payload = {
        "status": "completed" if exit_code == 0 and not error else "failed",
        "updater": chosen["id"], "path": resolved, "exit_code": exit_code,
        "error": error, "duration_ms": duration, "lines": lines,
        "version_after": after.version,
        "finished_at": dbmod.now_ms(),
        "restart_required": True,
        "note": ("ComfyUI was updated. Restart ComfyUI, then re-scan the vault "
                 "so new bundled workflows and node classes are picked up."),
    }
    with _run_lock:
        _run_state.update(payload)
        _run_state["running"] = False
    UPDATE_CHANNEL.publish("done", payload)


# ---------------------------------------------------------------------------
# Opening a workflow inside ComfyUI
# ---------------------------------------------------------------------------
#
# What ComfyUI 1.49.6 will and will not open from a URL - established by reading
# the frontend this install actually serves, not by assuming a URL shape.
#
# The served frontend is ``comfyui_frontend_package``.  Its router declares one
# application route ("/"), and the only query parameters any code in it reads
# are ``template``, ``source``, ``mode`` and ``share`` (plus the sign-in ones).
# There are three URL loaders and no more: the template loader
# (``?template=<name>&source=<default|module>``), the cloud share loader
# (``?share=<id>``, which needs an account), and an empty stub.
#
# ``source=default`` fetches ``/templates/<name>.json`` - the official templates
# distribution.  Any other ``source`` fetches
# ``/api/workflow_templates/<source>/<name>.json``, and ComfyUI's own server
# (``app/custom_node_manager.py``) mounts exactly that as a static directory for
# every *loaded* node package, for each of the five folder names below, one
# level deep.  Both ends also constrain the parameters: the frontend rejects
# anything that does not match ``^[A-Za-z0-9_.-]+$``.
#
# So a bundled example graph has a real deep link, and a workflow in
# ``user\default\workflows`` has none - no loader in this build reads a user
# workflow path out of the URL.  For those, the honest answer is to open ComfyUI
# and name the file the owner has to pick from the Workflows sidebar.  A link
# that silently does nothing would be worse than saying so plainly.

#: Folder names ComfyUI's own server serves example graphs from, in its order.
EXAMPLE_WORKFLOW_DIRS = ("example_workflows", "example", "examples",
                         "workflow", "workflows")

#: The frontend refuses a template/source parameter that does not match this.
TEMPLATE_PARAM_RE = re.compile(r"^[A-Za-z0-9_.-]+$")

CUSTOM_NODES_DIR = "custom_nodes"

#: The frontend package whose sources the rules above were read from.  Reported
#: with every plan, so a future frontend that changes them is visible.
DEEP_LINK_VERIFIED_AGAINST = "comfyui_frontend_package 1.49.6"

#: Launcher scripts a portable build keeps beside the ComfyUI folder.
LAUNCHER_GLOB = "run_*.bat"
#: Preferred first when several exist.  Discovery still lists every one found.
LAUNCHER_PREFERRED = ("run_nvidia_gpu.bat", "run_gpu.bat", "run_cpu.bat")
_PORT_ARG_RE = re.compile(r"--port[=\s]+(\d{2,5})")
MAX_LAUNCHER_BYTES = 64 * 1024

#: SECURITY_REVIEW S-21.  ``run_*.bat`` is a glob, not a name, and on a portable
#: build the folder it is globbed in is the *parent* of the ComfyUI folder -
#: which for the owner's install is a drive root.  A batch file that lands there
#: (an archive extracted one level too high, an installer, a downloaded script)
#: would otherwise be nominated as "a way to start ComfyUI" on the strength of
#: its filename alone.  A launcher for this install starts ComfyUI, so it names
#: ComfyUI's entry point; requiring that is evidence in the same spirit as C8.3's
#: "discovery, not assumption", and it is what separates a real launcher from a
#: file that merely matches the pattern.  It is one layer of several - the
#: verified-install gate, the cmd-metacharacter gate and the verbatim path
#: confirmation are the others - and is deliberately not claimed as proof of
#: intent on its own.
LAUNCHER_EVIDENCE = ("main.py", "python_embed", "comfyui")
#: Without this the script is not offered at all.
LAUNCHER_REQUIRED_EVIDENCE = "main.py"

#: How long a cold start may take before the wait gives up and says so.
LAUNCH_TIMEOUT_S = 300
#: Seconds between port probes while waiting for a start.
LAUNCH_POLL_S = 1.0

LAUNCH_CHANNEL = progress.bus("comfyui_launch")

_launch_lock = threading.Lock()
_launch_state: dict = {"status": "idle"}


def _read_text_capped(path: Path, limit: int = MAX_LAUNCHER_BYTES) -> str:
    try:
        with open(long_path(path), "rb") as handle:
            return handle.read(limit).decode("utf-8", "replace")
    except OSError:
        return ""


def _launcher_id(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", name.lower()).strip("_") or "launcher"


def discover_launchers(root: Path, parent: Path | None,
                       python_home: Path | None) -> list[dict]:
    """Every way to *start* THIS install, discovered the way C8.3 discovers
    updaters: probed on disk, reported with a resolved absolute path, never
    assumed and never hard-coded.

    The port matters as much as the path.  A portable launcher pins it on its
    command line (``--port 8188``), so it is read out of the script rather than
    guessed, and the plan can name the URL that will actually answer.

    Nothing is offered unless the configured folder is a *verified* ComfyUI
    install (S-20) and the script itself carries evidence that it starts this
    install (S-21).  Nominating an executable is the first half of running it.
    """
    found: list[dict] = []
    if missing_install_proof(root):
        return found
    if parent is not None:
        try:
            candidates = sorted(parent.glob(LAUNCHER_GLOB),
                                key=lambda p: p.name.lower())
        except OSError:
            candidates = []
        for path in candidates:
            if not path.is_file():
                continue
            text = _read_text_capped(path)
            lowered = text.lower()
            if LAUNCHER_REQUIRED_EVIDENCE not in lowered:
                log.info("ignoring %s: it matches %s but does not start ComfyUI",
                         path.name, LAUNCHER_GLOB)
                continue
            match = _PORT_ARG_RE.search(text)
            port = int(match.group(1)) if match else None
            if port is not None and not (1 <= port <= 65535):
                # A script may say anything; a port that is not a port would
                # reach socket.connect_ex and raise OverflowError inside the
                # launch thread (S-23).
                port, match = None, None
            found.append(_mark_cmd_hazard({
                "id": _launcher_id(path.stem),
                "kind": "batch",
                "label": path.name,
                "path": str(path),
                "working_dir": str(parent),
                "command": [str(path)],
                "port": port,
                "port_source": "launcher command line" if match else None,
                "evidence": [marker for marker in LAUNCHER_EVIDENCE
                             if marker in lowered],
                "available": True,
                "recommended": False,
                "note": ("A launcher script that ships with this build. It is run "
                         "exactly as it is on disk; the vault adds no arguments."),
            }))
    main_py = root / "main.py"
    if python_home is not None and main_py.is_file():
        exe = python_home / "python.exe"
        if not exe.is_file():
            exe = python_home / "bin" / "python"
        if exe.is_file():
            found.append({
                "id": "python_main",
                "kind": "python",
                "label": "python main.py in the ComfyUI folder",
                "path": str(exe),
                "working_dir": str(root),
                "command": [str(exe), "-s", str(main_py)],
                "port": None, "port_source": None, "evidence": ["main.py"],
                "available": True, "recommended": False,
                "note": ("Starts ComfyUI with the interpreter that ships with it. "
                         "Used when no launcher script was found beside it."),
            })
    for name in LAUNCHER_PREFERRED:
        for entry in found:
            if entry["kind"] == "batch" and entry.get("available") \
                    and entry["label"].lower() == name:
                entry["recommended"] = True
                break
        if any(e["recommended"] for e in found):
            break
    usable = [e for e in found if e.get("available")]
    if usable and not any(e["recommended"] for e in usable):
        usable[0]["recommended"] = True
    return found


def resolve_launcher(launcher_id: str | None = None, cfg=None) -> dict:
    install = probe(cfg)
    if not install.launchers:
        missing = missing_install_proof(install.root)
        raise NotFoundError(
            ("The configured ComfyUI folder is not a verified install, so no "
             "way to start it is offered. A real install carries "
             "comfyui_version.py, main.py and models/."
             if missing else
             "No way to start ComfyUI was found for this installation."),
            details={"comfyui_path": str(install.root) if install.root else None,
                     "flavour": install.flavour,
                     "missing": missing,
                     "looked_for": [f"{LAUNCHER_GLOB} beside the ComfyUI folder",
                                    "main.py with the interpreter that ships with it"],
                     "hint": "Start ComfyUI yourself, then open the workflow."},
        )
    if launcher_id:
        for entry in install.launchers:
            if entry["id"] == launcher_id:
                chosen = entry
                break
        else:
            raise NotFoundError(
                f"'{launcher_id}' is not a launcher this install offers.",
                details={"available": [e["id"] for e in install.launchers]})
    else:
        chosen = next((e for e in install.launchers if e["recommended"]),
                      install.launchers[0])
    if not chosen.get("available"):
        raise ConflictError(f"{chosen['label']} was found but cannot be run.",
                            details={"launcher": chosen["id"],
                                     "path": chosen.get("path"),
                                     "reason": chosen.get("unsafe_reason"),
                                     "note": chosen.get("note")})
    return chosen


def _path_parts(value: str) -> list[str]:
    text = str(value or "").replace("/", "\\")
    return [p for p in text.split("\\") if p and p != "."]


def deep_link_for(abs_path: str | None) -> dict:
    """Whether ComfyUI can be told to open THIS file, and with which parameters.

    Answers with a machine-readable ``reason`` when it cannot, because the UI has
    to explain the fallback rather than offer a link that quietly does nothing.
    """
    out: dict = {"supported": False, "reason": None, "explanation": None,
                 "params": None, "query": None, "source": None, "template": None,
                 "verified_against": DEEP_LINK_VERIFIED_AGAINST}
    parts = _path_parts(abs_path or "")
    if not parts:
        out["reason"] = "no_path"
        out["explanation"] = "This workflow has no file on disk to open."
        return out

    lowered = [p.lower() for p in parts]
    stem = parts[-1].rpartition(".")[0] or parts[-1]

    if CUSTOM_NODES_DIR in lowered:
        rest = parts[lowered.index(CUSTOM_NODES_DIR) + 1:]
        if len(rest) != 3 or rest[1].lower() not in EXAMPLE_WORKFLOW_DIRS:
            out["reason"] = "not_served_by_comfyui"
            out["explanation"] = (
                "ComfyUI serves only the example graphs sitting directly in one "
                "of " + ", ".join(EXAMPLE_WORKFLOW_DIRS) + " inside a node "
                "package folder. This file is elsewhere in the package, so it "
                "has no address ComfyUI answers on.")
            return out
        module = rest[0]
        if module.lower().endswith(".disabled"):
            out["reason"] = "package_disabled"
            out["explanation"] = (
                f"The node package '{module}' is disabled, so ComfyUI does not "
                "load it and does not serve its example graphs.")
            return out
        if not TEMPLATE_PARAM_RE.match(module) or not TEMPLATE_PARAM_RE.match(stem):
            offender = stem if not TEMPLATE_PARAM_RE.match(stem) else module
            out["reason"] = "name_not_url_addressable"
            out["explanation"] = (
                "ComfyUI accepts only letters, digits, dot, dash and underscore "
                f"in its template and source parameters. '{offender}' contains "
                "something else, so it cannot be named in a URL.")
            return out
        out.update({
            "supported": True, "template": stem, "source": module,
            "params": {"template": stem, "source": module},
            "query": f"?template={stem}&source={module}",
            "explanation": (
                "ComfyUI serves this package's example graphs at "
                f"/api/workflow_templates/{module}/, so it opens this graph by "
                f"name. It works while '{module}' is loaded by ComfyUI."),
        })
        return out

    if "templates" in lowered and any(
            p.startswith("comfyui_workflow_templates") for p in lowered):
        if not TEMPLATE_PARAM_RE.match(stem):
            out["reason"] = "name_not_url_addressable"
            out["explanation"] = (
                "Official template names must be letters, digits, dot, dash and "
                f"underscore; '{stem}' is not.")
            return out
        out.update({
            "supported": True, "template": stem, "source": "default",
            "params": {"template": stem, "source": "default"},
            "query": f"?template={stem}&source=default",
            "explanation": "An official template, which ComfyUI opens by name.",
        })
        return out

    out["reason"] = "user_workflow_has_no_deep_link"
    out["explanation"] = (
        "This is one of your own workflow files. " + DEEP_LINK_VERIFIED_AGAINST
        + " has no URL parameter that opens a file from the user workflows "
          "folder - its only workflow URL loaders are the template loader and "
          "the cloud share loader. ComfyUI is opened at its own address and you "
          "pick the file from the Workflows sidebar.")
    return out


def base_url(port: int) -> str:
    return f"http://127.0.0.1:{int(port)}/"


def _port_for(running: dict, launcher: dict | None) -> tuple[int, str]:
    if running.get("ports"):
        return int(running["ports"][0]), "the port ComfyUI is answering on"
    if launcher and launcher.get("port"):
        return int(launcher["port"]), "the --port argument in the launcher script"
    return COMFYUI_PORTS[0], "ComfyUI's default port; nothing else was measurable"


def user_workflows_dir(cfg=None) -> Path | None:
    cfg = cfg or config_service.get_config()
    if cfg.comfyui_path is None:
        return None
    return Path(normalize(cfg.comfyui_path)) / "user" / "default" / "workflows"


def _workflow_row(uid: str) -> dict:
    from .queries import tags_query, workflows_query

    kind, workflow_id = tags_query.parse_uid(uid)
    if kind != "workflow":
        raise ValidationError("Only a workflow can be opened in ComfyUI.",
                              details={"uid": uid, "expected": "workflow:<id>"})
    row = workflows_query.get_workflow(workflow_id)
    if row is None:
        raise NotFoundError("No such workflow.", details={"uid": uid})
    return row


def copy_plan(row: dict, cfg=None) -> dict:
    """What copying this file into the owner's ComfyUI workflows folder means.

    Deliberately honest about what it buys: the copy makes the graph appear in
    ComfyUI's Workflows sidebar.  It does **not** create a deep link, because
    this frontend has none for user workflows.  Offering it as "this makes the
    link work" would be a lie told by a progress bar.
    """
    target_dir = user_workflows_dir(cfg)
    plan: dict = {
        "possible": False, "needed": False, "reason": None,
        "destination": None, "target_dir": str(target_dir) if target_dir else None,
        "exists": False, "creates_deep_link": False, "note": None,
    }
    abs_path = row.get("abs_path")
    if not abs_path or target_dir is None:
        plan["reason"] = "no_comfyui_path"
        return plan
    source = Path(normalize(abs_path))
    if is_contained(source, target_dir):
        plan["reason"] = "already_in_the_workflows_folder"
        plan["note"] = ("This file already lives in your ComfyUI workflows "
                        "folder, so it is already in the Workflows sidebar.")
        return plan

    name = source.name
    if not name.lower().endswith(".json"):
        name = name + ".json"
    destination = target_dir / name
    plan.update({
        "possible": True, "needed": True,
        "destination": str(destination),
        "exists": Path(long_path(destination)).exists(),
        "note": ("Copies the file into your ComfyUI installation so it appears "
                 "in ComfyUI's Workflows sidebar. It does not create a link - "
                 + DEEP_LINK_VERIFIED_AGAINST + " cannot open a user workflow "
                 "from a URL - and it never overwrites a file already there."),
    })
    if plan["exists"]:
        plan["reason"] = "destination_exists"
        plan["possible"] = False
    return plan


def open_workflow_plan(uid: str, launcher_id: str | None = None, cfg=None) -> dict:
    """Everything that would happen, shown before anything happens."""
    cfg = cfg or config_service.get_config()
    row = _workflow_row(uid)
    running = is_running()
    install = probe(cfg)

    launcher: dict | None = None
    launcher_error: str | None = None
    try:
        launcher = resolve_launcher(launcher_id, cfg)
    except (NotFoundError, ConflictError) as exc:
        launcher_error = exc.message

    port, port_reason = _port_for(running, launcher)
    link = deep_link_for(row.get("abs_path"))
    url = base_url(port) + (link["query"] or "")
    copy = copy_plan(row, cfg)

    steps: list[str] = []
    if running["running"]:
        steps.append(f"ComfyUI is already answering on port {port}. "
                     "Nothing is started.")
    elif launcher is not None:
        steps.append(f"Start ComfyUI by running {launcher['path']} - a separate, "
                     "explicit confirmation that names that exact file.")
        steps.append(f"Wait for 127.0.0.1:{port} to accept a connection, for up "
                     f"to {LAUNCH_TIMEOUT_S // 60} minutes. A cold start loads "
                     "every installed node package and is not quick.")
    else:
        steps.append("No launcher was found, so ComfyUI has to be started by hand.")
    if link["supported"]:
        steps.append(f"Open {url} - ComfyUI loads the graph itself.")
    else:
        steps.append(f"Open {url} and pick this workflow from ComfyUI's Workflows "
                     "sidebar.")

    return {
        "uid": row["uid"], "workflow_id": row["id"], "name": row["name"],
        "abs_path": row.get("abs_path"), "rel_path": row.get("rel_path"),
        "origin": row.get("origin"), "origin_package": row.get("origin_package"),
        "origin_label": row.get("origin_label"),
        "running": running,
        "port": port, "port_reason": port_reason,
        "url": url,
        "open_method": "deep_link" if link["supported"] else "manual",
        "deep_link": link,
        "manual_hint": (None if link["supported"] else
                        "In ComfyUI, open the Workflows sidebar and choose "
                        f"{row['name']}."),
        "launcher": launcher,
        "launcher_confirm_path": (launcher or {}).get("path"),
        "launcher_alternatives": [e for e in install.launchers
                                  if launcher is None or e["id"] != launcher["id"]],
        "launcher_error": launcher_error,
        "copy": copy,
        "steps": steps,
        "needs_start": not running["running"],
        "can_open": bool(running["running"] or launcher is not None),
        "blocked_reason": (None if running["running"] or launcher is not None
                           else "no_launcher_found"),
        "frontend_version": install.packages.get("comfyui_frontend_package"),
        "comfyui_version": install.version,
    }


def copy_into_user_workflows(uid: str, *, confirm_destination: str, cfg=None) -> dict:
    """Copy one workflow into the owner's ComfyUI workflows folder.

    A write into the ComfyUI installation, so it carries the same shape of
    consent the updater does: the caller must name the destination it was shown.
    It never overwrites, and both ends are resolved through ``pathsafe`` against
    the configured roots - the vault writes only where the vault already reaches.
    """
    cfg = cfg or config_service.get_config()
    row = _workflow_row(uid)
    plan = copy_plan(row, cfg)
    if not plan["possible"]:
        raise ConflictError(
            "This workflow cannot be copied into the ComfyUI workflows folder.",
            details={"reason": plan["reason"], "destination": plan["destination"]})

    resolved = str(normalize(plan["destination"]))
    if not confirm_destination or str(normalize(confirm_destination)) != resolved:
        raise ValidationError(
            "The copy was not confirmed for the path it would actually write.",
            details={"resolved_destination": resolved,
                     "confirm_destination": confirm_destination,
                     "hint": "Send confirm_copy_destination exactly as returned "
                             "by the open-workflow plan."},
        )

    destination = Path(resolved)
    validate_filename(destination.name)
    resolve_within_roots(destination.parent, cfg.roots)
    # SECURITY_REVIEW S-22.  "Inside a configured root" is the vault-wide rule;
    # this route promises something narrower - "into your ComfyUI workflows
    # folder" - so it is checked separately.  ``normalize`` has already collapsed
    # any ``..`` and resolved any junction, so this compares final paths.
    target_dir = user_workflows_dir(cfg)
    if target_dir is None or not is_contained(destination.parent, target_dir):
        raise ValidationError(
            "A workflow may only be copied into the ComfyUI workflows folder.",
            details={"destination": resolved,
                     "target_dir": str(target_dir) if target_dir else None})
    source = Path(normalize(row["abs_path"]))
    resolve_within_roots(source, cfg.roots)

    if Path(long_path(destination)).exists():
        raise ConflictError(
            "A file with that name is already in the ComfyUI workflows folder.",
            details={"destination": resolved})
    try:
        os.makedirs(long_path(destination.parent), exist_ok=True)
        # "xb", not shutil.copyfile: the existence check above is a courtesy that
        # gives a good message, but only an exclusive create makes "it never
        # overwrites" true for a file that appears in between.
        with open(long_path(source), "rb") as src, \
                open(long_path(destination), "xb") as dst:
            shutil.copyfileobj(src, dst)
    except OSError as exc:
        raise ConflictError("The workflow could not be copied.",
                            details={"destination": resolved,
                                     "error": str(exc)[:300]}) from exc
    return {"copied": True, "destination": resolved,
            "note": ("Copied into your ComfyUI workflows folder. Re-scan the "
                     "vault to index the new copy.")}


def launch_status() -> dict:
    state = dict(_launch_state)
    state["running"] = state.get("status") == "starting"
    return state


def start_comfyui(launcher_id: str | None, *, confirm_path: str,
                  port: int | None = None, url: str | None = None,
                  trigger: str = "api") -> dict:
    """Start ComfyUI.  Never implicit, never a side effect of "open".

    ``confirm_path`` must equal the resolved absolute path of the launcher that
    was shown, exactly as the updater requires.  Someone who clicked "open a
    workflow" has not agreed to start a program: that is a second question with
    its own answer, and this is where the answer is checked.
    """
    chosen = resolve_launcher(launcher_id)
    resolved = str(normalize(chosen["path"])) if chosen.get("path") else ""
    if not confirm_path or str(normalize(confirm_path)) != resolved:
        raise ValidationError(
            "Starting ComfyUI was not confirmed for the path that would run.",
            details={"resolved_path": resolved, "confirm_path": confirm_path,
                     "hint": "Send confirm_launcher_path exactly as returned by "
                             "the open-workflow plan."},
        )
    _refuse_a_reparsed_command(chosen)
    running = is_running()
    if running["running"]:
        raise ConflictError("ComfyUI is already running.", details=running)
    if _run_state.get("status") == "running":
        raise ConflictError("The ComfyUI updater is running. Wait for it to finish.",
                            details={"started_at": _run_state.get("started_at")})

    chosen_port = int(port or chosen.get("port") or COMFYUI_PORTS[0])
    target = url or base_url(chosen_port)

    with _launch_lock:
        if _launch_state.get("status") == "starting":
            raise ConflictError(
                "ComfyUI is already being started.",
                details={"started_at": _launch_state.get("started_at")})
        _launch_state.clear()
        _launch_state.update({
            "status": "starting", "launcher": chosen["id"], "path": resolved,
            "command": chosen["command"], "working_dir": chosen.get("working_dir"),
            "port": chosen_port, "url": target, "started_at": dbmod.now_ms(),
            "trigger": trigger, "pid": None, "ready": False, "error": None,
            "elapsed_ms": 0, "exit_code": None,
        })

    thread = threading.Thread(target=_start_comfyui_thread,
                              args=(chosen, resolved, chosen_port, target),
                              daemon=True, name="comfyui-launch")
    thread.start()
    LAUNCH_CHANNEL.publish("phase", {"phase": "starting", "launcher": chosen["id"],
                                     "path": resolved, "port": chosen_port,
                                     "url": target})
    return {
        "started": True, "launcher": chosen["id"], "label": chosen["label"],
        "path": resolved, "working_dir": chosen.get("working_dir"),
        "port": chosen_port, "url": target,
        "stream": "/api/v1/comfyui/launch/stream",
        "timeout_s": LAUNCH_TIMEOUT_S,
        "started_at": _launch_state["started_at"],
    }


def _port_open(port: int, timeout: float = 0.25) -> bool:
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    sock.settimeout(timeout)
    try:
        return sock.connect_ex(("127.0.0.1", int(port))) == 0
    except (OSError, OverflowError, ValueError):
        # A port outside 0-65535 raises OverflowError, not OSError, and this
        # runs on the launch thread where an escape would strand the state.
        return False
    finally:
        sock.close()


def _start_comfyui_thread(chosen: dict, resolved: str, port: int, url: str) -> None:
    started = time.perf_counter()
    error: str | None = None
    proc = None
    try:
        # A list argv with shell=False.  The executable is one of the paths
        # `discover_launchers` found on disk and the caller confirmed by name;
        # nothing here is assembled from user text.
        #
        # That is necessary and not sufficient (SECURITY_REVIEW S-19): a .bat
        # target is run through cmd.exe by CreateProcess, which re-parses this
        # command line, so `cmd_line_hazard` has already refused a path cmd
        # would read as syntax.  Do not remove that check on the strength of
        # "but it is a list argv".
        #
        # A new console is deliberate: ComfyUI outlives this app, and its own
        # window is how the owner watches it and closes it.
        proc = subprocess.Popen(  # noqa: S603
            list(chosen["command"]),
            cwd=chosen.get("working_dir") or None,
            stdin=subprocess.DEVNULL,
            creationflags=getattr(subprocess, "CREATE_NEW_CONSOLE", 0),
        )
    except OSError as exc:
        error = str(exc)[:400]
        LAUNCH_CHANNEL.publish("error", {"message": error})
    else:
        _launch_state["pid"] = proc.pid
        LAUNCH_CHANNEL.publish("phase", {"phase": "spawned", "pid": proc.pid,
                                         "port": port})

    ready = False
    exit_code: int | None = None
    try:
        if proc is not None:
            last_report = 0.0
            while True:
                elapsed = time.perf_counter() - started
                if _port_open(port):
                    ready = True
                    break
                exit_code = proc.poll()
                if exit_code is not None:
                    error = (f"The launcher exited with code {exit_code} before "
                             f"127.0.0.1:{port} accepted a connection.")
                    break
                if elapsed > LAUNCH_TIMEOUT_S:
                    error = (f"ComfyUI did not accept a connection on "
                             f"127.0.0.1:{port} within {LAUNCH_TIMEOUT_S} "
                             "seconds. It may still be loading - its console "
                             "window says where it is.")
                    break
                if elapsed - last_report >= 2.0:
                    last_report = elapsed
                    _launch_state["elapsed_ms"] = int(elapsed * 1000)
                    LAUNCH_CHANNEL.publish(
                        "waiting",
                        {"elapsed_ms": int(elapsed * 1000), "port": port,
                         "note": "waiting for ComfyUI to accept connections"})
                time.sleep(LAUNCH_POLL_S)
    except Exception as exc:
        # Whatever happens up there, the state machine has to leave "starting"
        # and the stream has to receive its terminal event.  A wait that ends
        # in an exception would otherwise wedge every later launch behind
        # "ComfyUI is already being started" and hold every SSE subscriber open.
        ready = False
        error = error or f"The start could not be watched: {str(exc)[:300]}"
        log.exception("comfyui launch watch failed")

    duration = int((time.perf_counter() - started) * 1000)
    payload = {
        "status": "ready" if ready else "failed",
        "ready": ready, "launcher": chosen["id"], "path": resolved,
        "port": port, "url": url, "error": error, "exit_code": exit_code,
        "elapsed_ms": duration, "duration_ms": duration,
        "pid": _launch_state.get("pid"),
        "finished_at": dbmod.now_ms(),
        "note": ("ComfyUI is accepting connections." if ready else
                 "ComfyUI was not reachable. Its console window shows why."),
    }
    with _launch_lock:
        _launch_state.update(payload)
        _launch_state["running"] = False
    if ready:
        LAUNCH_CHANNEL.publish("ready", payload)
    else:
        LAUNCH_CHANNEL.publish("error", {**payload,
                                         "message": error or "start failed"})
    LAUNCH_CHANNEL.publish("done", payload)


def open_workflow(uid: str, *, launcher_id: str | None = None, start: bool = False,
                  confirm_launcher_path: str | None = None,
                  copy_to_user_workflows: bool = False,
                  confirm_copy_destination: str | None = None,
                  trigger: str = "api") -> dict:
    """Open one workflow in ComfyUI, starting ComfyUI first only when asked.

    Three separate consents, because these are three separate acts: opening a
    URL, writing a file into the ComfyUI install, and starting a program.
    """
    cfg = config_service.get_config()
    plan = open_workflow_plan(uid, launcher_id, cfg)

    result: dict = {
        "uid": plan["uid"], "name": plan["name"], "url": plan["url"],
        "open_method": plan["open_method"], "deep_link": plan["deep_link"],
        "manual_hint": plan["manual_hint"], "port": plan["port"],
        "copied": False, "copy_destination": None, "copy_note": None,
        "started": False, "already_running": bool(plan["running"]["running"]),
        "ready": bool(plan["running"]["running"]),
        "launcher": None, "launcher_path": None, "stream": None,
        "timeout_s": None, "started_at": None, "note": None,
    }

    if copy_to_user_workflows:
        copied = copy_into_user_workflows(
            uid, confirm_destination=confirm_copy_destination or "", cfg=cfg)
        result["copied"] = True
        result["copy_destination"] = copied["destination"]
        result["copy_note"] = copied["note"]

    if result["already_running"]:
        result["note"] = (
            "ComfyUI is already running; the vault started nothing. "
            + ("Open the URL and ComfyUI loads the graph."
               if plan["open_method"] == "deep_link"
               else (plan["manual_hint"] or "")))
        return result

    if not start:
        raise ConflictError(
            "ComfyUI is not running. Starting it needs its own confirmation.",
            details={"launcher": (plan["launcher"] or {}).get("id"),
                     "label": (plan["launcher"] or {}).get("label"),
                     "confirm_launcher_path": plan["launcher_confirm_path"],
                     "url": plan["url"],
                     "hint": "Send start=true with confirm_launcher_path set to "
                             "the exact path the plan showed."},
        )

    launch = start_comfyui(launcher_id, confirm_path=confirm_launcher_path or "",
                           port=plan["port"], url=plan["url"], trigger=trigger)
    result.update({
        "started": True, "ready": False,
        "launcher": launch["launcher"], "launcher_path": launch["path"],
        "stream": launch["stream"], "timeout_s": launch["timeout_s"],
        "started_at": launch["started_at"], "port": launch["port"],
        "url": launch["url"],
        "note": ("ComfyUI is starting. Watch the launch stream and open the URL "
                 "when it reports ready."),
    })
    return result


# ---------------------------------------------------------------------------
# Report shaping
# ---------------------------------------------------------------------------

def report(cfg=None) -> dict:
    """The read-only C8 panel payload."""
    install = probe(cfg)
    if install.root is None:
        return {"configured": False, "comfyui_path": None, "version": None,
                "flavour": "unknown", "updaters": [], "launchers": [],
                "packages": {}, "running": {"running": False, "ports": []}}
    return {
        "configured": True,
        "comfyui_path": str(install.root),
        "install_parent": str(install.parent) if install.parent else None,
        "version": install.version,
        "version_source": install.version_source,
        "flavour": install.flavour,
        "flavour_evidence": install.flavour_reasons,
        "python_home": install.python,
        "git": install.git,
        "packages": install.packages,
        "updaters": install.updaters,
        "recommended_updater": next(
            (u["id"] for u in install.updaters if u["recommended"]), None),
        "launchers": install.launchers,
        "recommended_launcher": next(
            (entry["id"] for entry in install.launchers if entry["recommended"]),
            None),
        "running": is_running(),
        "update_status": update_status(),
        "launch_status": launch_status(),
    }
